### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#1]
When I try to compile using the Visual Studio 2022 "Project from existing code" I am getting those errors:
Build started...
1>------ Build started: Project: Agents2Tasks, Configuration: Debug x64 ------
1>allocator.cpp
1>C:\tools\Agents2Tasks\src\allocator.h(5,10): fatal  error C1083: Cannot open include file: '../../PathFinder/src/GraphTheory.h': No such file or directory
1>cGUI.cpp
1>C:\tools\Agents2Tasks\src\cGUI.cpp(1,10): fatal  error C1083: Cannot open include file: 'inputbox.h': No such file or directory
1>main.cpp
1>C:\tools\Agents2Tasks\src\main.cpp(7,10): fatal  error C1083: Cannot open include file: 'wex.h': No such file or directory
1>Generating Code...
1>Done building project "Agents2Tasks.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 5:32 AM and took 02.293 seconds ==========

**Comment by JamesBremner** [comment]
Do not use Visual Studio.  ( The compiler is a  microsoft specific oddity )

You can use Visual Studio Code OR run the makefile directly

The errors you are seeing are because you have not downloaded the required libraries.  Please follow the build instructions on how to get what you need and where to install them.  https://github.com/JamesBremner/Agents2Tasks/wiki/Build-Instructions

**Comment by JamesBremner** [comment]
Asked in a duplicate issue:

> Can you specify that the g++ executable is found in [drive letter]:\msys64\ucrt64\bin
> What is the configuration command to compile Agents2Tasks?

The g++ compiler will be installed wherever you chose to install it.  The important point is that it is present in your path.  You can check with this command

`>g++ -v`

Details are in the build instructions.

**Comment by JamesBremner** [comment]
To run the build you need to run makefile.  The easiest way to do that is to unstall VSCODE and use the build command.  However, if you want to use the command line, you will needthis:

`Agents2Tasks>mingw32-make -f .vscode/makefile starter`

**Comment by rejkid** [comment]
I am getting this error when running  mingw32-make -f .vscode/makefile starter:

C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lboost_system-mgw11-mt-x64-1_78: No such file or directory
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lboost_program_options-mgw11-mt-x64-1_78: No such file or directory
collect2.exe: error: ld returned 1 exit status
.vscode/makefile:41: recipe for target 'starter' failed
mingw32-make: *** [starter] Error 1

**Comment by JamesBremner** [comment]
You need to update your clone of this repo.

**Comment by rejkid** [comment]
You mean clone it again  right?

**Comment by JamesBremner** [comment]
You do not need to do a full clone.  Just a fetch and a pull.

**Comment by JamesBremner** [comment]
Like this:

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/a112342d-9d87-42a1-9a6b-4d7777a3163a)

**Comment by JamesBremner** [comment]
A note about build error reports:  Please do not post partial build logs.  I need to see the **entire** build log.

**Comment by rejkid** [comment]
OK. successfully built the starter.exe. Its 3am Sydney time. I will continue in the morning. Thank you for your help again

**Comment by JamesBremner** [comment]
Sydney, Australia?

**Comment by rejkid** [comment]
Yep, Why?

**Comment by JamesBremner** [comment]
Just curious.  I have clients all around the world - it is fun to imagine sticking a new pin into a new corner of the world map.

**Comment by rejkid** [comment]
Ahh. OK. Goodnight. Do you mind if I have some new questions later?

**Comment by JamesBremner** [comment]
Of course not.  Remember to assign your new issues to me, so that they appear in my todo list.

**Comment by rejkid** [comment]
You mean use this issue tool or something else? How do I assign it to you?

**Comment by JamesBremner** [comment]
To assign an issue, click on Assignees on top right

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/8655acff-5aa8-4a12-9e8e-6c28714953d0)

**Comment by JamesBremner** [comment]
According to your profile you have been a github user for many years.  Quite active too.

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/a1b30379-398f-4379-989b-f7af201e141d)

So, I am curious:  how you could possibly not know how to assign an issue!

**Comment by JamesBremner** [comment]
Build command is now

Agents2Tasks>mingw32-make -f .vscode/makefile a2t

**Comment by rejkid** [comment]
I have never ever reported any issue. I have used github to store/retrieve my projects. This is new to me.
