### ISSUE TITLE
Calling Agent2Task from c#

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#11]
James, I have run into another problem. This is not a2t problem but let me explain what the issue is. a2t is an external console application that reads the data input file and writes an output file with the result. The problem is that if I call a2t console app from c# it always outputs an empty file (I guess some security issue). If I do this process manually by executing the a2t console app by myself (passing input and output files as arguments) it creates non empty output result file as expected. People on internet suggested to call into Dll if I have access to it. Is it possible to compile a2t as dll with one function to call? If not then don't worry about it I will have to come up with some other solution.

**Comment by JamesBremner** [comment]
I would not know how to do this in c#.

You will need to find the c# equivalent of the C standard library method to run a separate process.

This looks like it might be a good place to start https://stackoverflow.com/a/181857/16582

**Comment by rejkid** [comment]
Yep. I tried that - this is classical calling external process from c# - unfortunately for the reasons above it does not work. It was suggested to me that if we turn the a2t into dll (if possible of course) I could call the method in c# from dll in the following way:
c# implementation:
[DllImport(@"a2t.dll")]
public static extern void run(string input, string output);

so in other words the a2d dll would be part of my server c# app and in this way I could call  a function to do agents to tasks assignment instead of creating a background process that seems to have some limitations.

**Comment by JamesBremner** [comment]
> (I guess some security issue)

I am almost certain that this is not the case.  I believe you are making some mistake in using the external process.

> turn the a2t into dll

This is a terrible idea.  If you do not know why, try googling "DLL Hell".

**Comment by rejkid** [comment]
It is quite possible that I am doing something wrong. I will keep trying, but I have spent hours on this programmatic running of a2t.
I would like to thank you very much for the time you spent on that and your patience with me. I really appreciate it. I will let you know how i go.

**Comment by JamesBremner** [comment]
Suggestion: Write a little 'hello world' C++ program.  ( i.e. writes 'hello world' to a text file )

Try running this program from C#.  

If this, the simplest possible program, does not work, then you can be sure you are doing something wrong and it is not something strange in A2T.

**Comment by rejkid** [comment]
Yep. I will try to do that. Thanks

**Comment by JamesBremner** [comment]
Here is how I would call A2TConsole from a C++ application

```
#include <fstream>
#include <wex.h>

class cGUI
{
public:
    cGUI()
        : fm(wex::maker::make()),
          bnStart(wex::maker::make<wex::button>(fm)),
          bnDisplay(wex::maker::make<wex::button>(fm)),
          plDisplay(wex::maker::make<wex::panel>(fm))
    {
        // App window
        fm.move({50, 50, 400, 400});
        fm.text("A2T Starter");

        // Start button
        bnStart.move(100, 50, 200, 30);
        bnStart.text("Start A2T");
        bnStart.events().click(
            []
            {
                std::string error;
                if (wex::free::startProcess(
                        "Agents2TasksConsole.exe ../dat/ex10.txt console.txt",
                        error))
                {
                    wex::msgbox("ERROR starting A2T " + error);
                }
            });

        // Display button
        bnDisplay.move(100, 100, 200, 30);
        bnDisplay.text("Display Results");
        bnDisplay.events().click(
            [this]
            {
                std::ifstream ifs("console.txt");
                if (!ifs.is_open())
                {
                    wex::msgbox("ERROR no output from A2T");
                    return;
                }
                std::string text;
                char ch;
                while (ifs.get(ch))
                    text += ch;
                plDisplay.text(text);
                plDisplay.update();

            });

        // Display
        plDisplay.move(0, 150, 400, 400);
        fm.show();
        fm.run();
    }
private:
    wex::gui &fm;
    wex::button &bnStart;
    wex::button &bnDisplay;
    wex::panel &plDisplay;
};

main()
{
    cGUI theGUI;
    return 0;
}
```

with the result

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/b518e042-def2-4c59-bcb9-5277fc800db5)

**Comment by JamesBremner** [comment]
As you will notice, I am using `wex::free::startProcess` to start A2TConsole.

https://github.com/JamesBremner/windex/blob/fe009cde5aa19c6dbebc730069241f5e00facf46/include/wex.h#L3514-L3572

startProcesss is a simple wrapper for the the windows API method CreateProcessA https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa

I would assume you can make a similar wrapper in C# based on this.

**Comment by rejkid** [comment]
I really appreciate the time you spent helping me. Thank you. I have found an example on github that works. It is very similar to the code I have. I am trying to understand why my code is not working.

**Comment by rejkid** [comment]
James . Should I close the issue?

**Comment by JamesBremner** [comment]
Does that mean you have the console application working in a separate process?
