### ISSUE TITLE
Console app error handling

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#12]
Assuming running the console app in a separate process ( #11 ) is now working, the question becomes: how do you want to handle errors?

**Option 1:**

A missing or empty output file indicates an error occurred.

Change required:  the console app needs to delete output file when it starts

Snag: No way for your code to report a hint to what went wrong

**Option 2:**

Output file contains an error report.

If you select this option we have to agree on an error report format

**Option 3:**

On error console app exits with a non-zero termination status, if possible indicating what went wrong

Depending on how you are running the process, checking the termination status might be the simplest for you to code.

**Comment by JamesBremner** [comment]
I have committed some basic error handling so you can experiment with this and decide how you want to handle errors in detail.

**Comment by rejkid** [comment]
1) I am always deleting output file before calling "Agents2TasksConsole.exe a2t.txt a2t_result.txt"
2) I agree - checking the termination status might be the simplest for you to code
3) I am currently experimenting with it

**Comment by JamesBremner** [comment]
0	OK
2	unknown
3	Bad command line parameters
10	Timeslot badly formatted
11    Timeslot out of order
12	Duplicate agent name
13	Duplicate timeslot
14	Timeslots out of order
14	Cannot open output file
15	Cannot open input file
16	Unit test failed

**Comment by JamesBremner** [comment]
Oops, error code 11 got lost somewhere.  I have updated the list.

**Comment by JamesBremner** [comment]
The console application codes are documented in the wiki at https://github.com/JamesBremner/Agents2Tasks/wiki/Console-status-codes

Going forward, I will be updating the wiki ( rather than this issue )

**Comment by rejkid** [comment]
Error codes tested - apart from:
17 - I was testing error code "Timeslot badly formatted" (10) with the following record-
 t 2023/10/220830 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC and I got error code 17
2/10  - don't know how to test
16 - I don't have Unit tests

**Comment by JamesBremner** [comment]
> 2 - don't know how to test

This is catch all for unknown errors.  For example, an exception thrown form the C standard library.  You do not need to test this.  If you ever get this error, run the application from the command line with the same input so you can see the error text.

16 - I don't have Unit tests

Yes you do.  I would expect you to run them first thing after you do a new build.  Otherwise you will miss any build problems that might occur.

From the readme:

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/080c3c5d-35c5-4048-865a-c81e5065bcf0)

**Comment by rejkid** [comment]
Running unit test with the usual input file terminates with the message:
"terminate called after throwing an instance of 'std::runtime error'"
