### ISSUE TITLE
Avoid assigning agents with rare capabilities to tasks that can be done by many agents

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#13]
Currently, the  agents2tasks algorithm is focused on minimizing the cost of assignments.

I have noticed that you tend to set all assignment costs equal to 1.  So the cost optimization is irrelevant.  I assume that you therefor want to optimize for the maximum number of tasks assigned in each timeslot ( funny thing: you never actually specified what you want to optimize for, all you said was 'solve' the problem )

If cost is equal, the current algorithm simply assigns tasks in first come, first served order.  This can cause agents to that have rare capabilities to be assigned to tasks that could have been dome by many other agents, which can in turn mean that they are not available for the  later tasks that only they could have done.

Here is a simple example that demonstrate the problem:

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/f922fdd6-67df-4cc9-a3b9-ec08bb08c881)

Because of the order in which the agents and tasks have been specified, Alice will be assigned to the cleaning task, when it would have been much more efficient to assign her to the later, teacher task that only she can do.

Solution: re-order the tasks so that agents with multiple capabilities are NOT assigned to tasks that many others could do.

**Comment by rejkid** [comment]
So I can understand it better.
1) Do you want me to re-order so that the agent with multiple task are at the end of the  "a" records
2) Remove from "a" records where multitasks are task are assigned those that can be done by others?

**Comment by JamesBremner** [comment]
This issue is assigned to you in test.  Please do not reassign it to me until you have tested it.

> Do you want me to ...

All you need to do is test this.  No changes to the input are required.

The sorting described was implemented yesterday in commit https://github.com/JamesBremner/Agents2Tasks/commit/16e6ba72a730729da1bcc1cb24e96b0d7925c276

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/35799b9f-7602-4a07-8a5c-ae0b51280f60)

**Comment by rejkid** [comment]
Works as expected. Input:
a Alice 1 teacher cleaner 
a Bob 1 cleaner 
t 202311091000 cleaner teacher 

produced output
A 202311091000 Alice to teacher
A 202311091000 Bob to cleaner
