### ISSUE TITLE
 Agent assigned two tasks in the same day:

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#14]
jblack@gmail.com is assigned two tasks in the same day:
A 202310220830 jblack@gmail.com&1961-03-24& to EMHC
A 202310221000 jblack@gmail.com&1961-03-24& to Acolyte

[a2t_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/13329872/a2t_result.txt)

**Comment by JamesBremner** [comment]
Duplicate of #15

**Comment by JamesBremner** [comment]
Agents are not assigned the **same task** in the same 2-day blocking period.  They are not assigned to different tasks in the same timeslot.

Please read #8 carefully.
