### ISSUE TITLE
Timeslots out of order at 202310221000

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#15]
Hi James - I sort of don't understand that one - why is the timeslot (in the file attached) out of order (returned error code is 2)?
[a2t.txt](https://github.com/JamesBremner/Agents2Tasks/files/13330735/a2t.txt)

**Comment by JamesBremner** [comment]
Cause: bug in timeslot sanity test

**Comment by JamesBremner** [comment]
> I run the a2t outside of my app and the error 11 issue still happens

Have you updated and rebuilt the repo?

**Comment by rejkid** [comment]
Yes. I did. git tells me that the repo is already up to date

**Comment by JamesBremner** [comment]
You are using the git command line?  You are making your life unnecessarily hard.  Please use the github desktop application ( as I suggested in the build instructions. )

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/a7ea3f66-493f-4ff6-bb9b-bb0f234ac846)

**Comment by JamesBremner** [comment]
Occurs to me that you might be using the 32 bit compiler, which would cause the timeslot time point to overflow.

To check

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/519d199e-1d4b-4adb-89ca-80b838458bc7)

**Comment by rejkid** [comment]
Yes. You are right.
![image](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/1309e748-0b1f-4928-a488-e30ddbb02822)

How do I switch to 64 bit version in Visual Studio Code?

**Comment by JamesBremner** [comment]
Please check that you have the latest version of the repo, using github desktop application.

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/9c7554ef-729c-43aa-9a8c-f9c1a14fa6d6)

**Comment by JamesBremner** [comment]
You are correct!

We both have the 32 bit compiler!!!

**Comment by rejkid** [comment]
Can you reproduce the problem?

**Comment by JamesBremner** [comment]
It is now fixed.  Please test with the latest version.

Did you not notice that I assigned this to you in test?

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/bd86d562-bef6-4cbe-9e41-62040aa74cc4)

**Comment by rejkid** [comment]
Thank you. It looks better, but does not produce any output for the time slot 202311050830 and 202311051000

**Comment by JamesBremner** [comment]
By that, I guess you mean that you no longer see the timeslots out of order error. If so, then please close this issue.

If you find a new problem, please open a new issue.

**Comment by rejkid** [comment]
The error "Timeslot out of order" is gone now.
