### ISSUE TITLE
No output for the timeslots  202311050830 and 202311051000

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#19]
Thank you. It looks better, but does not produce any output for the time slot 202311050830 and 202311051000

A 202310220830 rejkid@gmail.com&1998-06-07& to Reader2
A 202310220830 ismith@gmail.com&1961-07-02&A to Acolyte
A 202310220830 rejkid@gmail.com&1961-03-24&A to Acolyte
A 202310220830 mwalsh@gmail.com&2010-01-01& to MAS
A 202310220830 rejkid@gmail.com&1992-08-28& to MAS
A 202310220830 jwhite@gmail.com&1961-03-24& to Reader1
A 202310220830 jblack@gmail.com&1961-03-24& to EMHC
A 202310220830 jsmith@gmail.com&1961-03-24& to EMHC
A 202310221000 jsmith@gmail.com&1961-03-24& to Reader2
A 202310221000 jblack@gmail.com&1961-03-24& to Acolyte
A 202310221000 osiekkolawy@gmail.com&1961-03-24&B to MAS
A 202310221000 rejkid@gmail.com&1961-07-02& to Reader1
A 202310221000 jwhite@gmail.com&1961-03-24& to EMHC
A 202310290830 jblack@gmail.com&1961-03-24& to Reader1

**Comment by JamesBremner** [comment]
Cause: bugs in parsing the timeslot timestamp

**Comment by rejkid** [comment]
Fixed. Visually inspected all output results.
