### ISSUE TITLE
Unit Test fails

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#20]
Reported in #12 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  20 Cannot parse timeslot timestamp
```

**Comment by JamesBremner** [comment]
Cause: Unit test code not updated to use YYYYMMDDHHSS timestamp format.  Recent improvements to the timestamp parsing are now rejecting the old format

**Comment by rejkid** [comment]
Unit test passed
