### ISSUE TITLE
 Assign agents from the same family to the same time slot

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#21]
Requested in #17 

 it would be a really good feature to assign agents from the same family (new concept) to the same time slot (so the family can be together doing their task).

**Comment by JamesBremner** [comment]
Currently, agents are sorted so that the 'cheapest' agents are assigned to tasks.

I do not think you are using this feature.

Assuming we remove the agent cost feature, then we could replace it with sorting by family.  This would have to be done after every assignment so that family members will be picked first for the remaining task in the same timeslot.

**Comment by JamesBremner** [comment]
> The only problem is that there can be few "Smith" 

It is the responsibility of the user to assign agents to unique families.

Maybe Smith_1, Smith_2 ...

Or, since you are, I believe, using SQLite for your database, just use the ROWID of the family.

**Comment by rejkid** [comment]
Or, have a restriction that the family must be using one e-mail address and then use that instead of family last name - just thinking loudly

**Comment by JamesBremner** [comment]
Check file format at https://github.com/JamesBremner/Agents2Tasks/wiki/File-format

**Comment by JamesBremner** [comment]
I took a look at the implementation details for this issue.  Turns out that there is no conflict between cost optimization and family grouping.  ( You simply set the 'cost' of all agents to be the same, just as you do now )

There is a question about prioritizing between family grouping ( this issue ) and the even distribution of work ( #5 ).  Suppose that there are two agents, our old friends Alice and Bob, who could be assigned to a task.  Alice shares a family group with another agent assigned to the same timeslot but has previously between assigned to several tasks in other timeslots.  Bob has no family group member assigned to this timeslot and has never previously been assigned to any task.  Who should get the job?

**Comment by JamesBremner** [comment]
Check updated file format at https://github.com/JamesBremner/Agents2Tasks/wiki/File-format

**Comment by JamesBremner** [comment]
Can you answer the question:  wjho should get the job, the agent with the same family group ( Alice ) or the agent with the smaller  number of assignments ( Bob )?

In the meantime: here is the code to for sorting agents by family group.

```
void cAllocator::sortAgents(
    const cSlot& slot )
{
    // prefer to assign agents that have family members already assigned to the slot
    std::stable_sort(
         myAgent.begin(), myAgent.end(),
        [&](const cAgent &a, const cAgent &b)       
        {
           return slot.hasFamily( a.family() );
        });
```


And here is some sample output for 1 timeslot ( so the work distribution is not relevant )

```
a Carol 1 A cleaner 
a Bob 1 B cleaner 
a Alice 1 A cleaner 
t 202311011000 cleaner cleaner 
A 202311011000 Alice to cleaner
A 202311011000 Carol to cleaner
```

Carol gets the second cleaner job because she is in the same group aas Alice

**Comment by rejkid** [comment]
Yep. The agent with the same group ( Alice ) would be preferable.

**Comment by JamesBremner** [comment]
OK.  I am ready to implement this when you assign it to me.

Note that I am also ready to implement #17 ( https://github.com/JamesBremner/Agents2Tasks/issues/17#issuecomment-1810638297 )

**Comment by rejkid** [comment]
I see only one problem with the current proposed solution:
In example like this one:
a Alice 1 awhite@gmail.com teacher
a Carol 1 A cleaner teacher
t 202311011000 teacher 

A 202311011000 Alice to teacher
A 202311011000 Carol to cleaner

If the output is like above then it might be wrong because Carol can be from the same family as Alice (iwhite@gmail.com) so they should be teachers together, but I specified Carol in group A because she is also a cleaner.

**Comment by JamesBremner** [comment]
Your example makes no sense.  The timeslot has just one task.  Why are two agent assigned to the timeslot.  There is no cleaner task for Carol to be assigned to!

**Comment by rejkid** [comment]
Sorry I meant :
a Alice 1 awhite@gmail.com teacher
a Carol 1 A cleaner teacher
**t 202311011000 teacher cleaner**

A 202311011000 Alice to teacher
A 202311011000 Carol to cleaner

**Comment by JamesBremner** [comment]
OK.  So what is wrong with that result?  The result would be the same if groups were not implemented.

**Comment by rejkid** [comment]
Yes . I agree. Nothing wrong with your algorithm.
Problem is that Carol can be from the same family as Alice so she should be scheduled together with Alice as teachers not a cleaner. Should they not. Maybe I am overthinking the whole process?

**Comment by JamesBremner** [comment]
> she should be scheduled together with Alice as teachers

There is only one teacher task in the timeslot.  So that is impossible

**Comment by rejkid** [comment]
You are right. What if there are two teachers like below?
Sorry James. I am trying to make sure that the result will be correct and we will not have to go back and correct it.

a Alice 1 awhite@gmail.com teacher
a Carol 1 A cleaner teacher
t 202311011000 teacher teacher cleaner

A 202311011000 Alice to teacher
A 202311011000 Carol to cleaner

**Comment by JamesBremner** [comment]
There are two agents.  So two tasks get assigned.  No more can be done, because you have run out of agents.

**Comment by rejkid** [comment]
OK. Lets implement it. I am itching to see the results

**Comment by JamesBremner** [comment]
Unit tests now pass.

```C++
   utname = "tid21-1";
    readstring(
        allocator,
        "a Carol 1 A cleaner\n"
        "a Bob 1 B cleaner\n"
        "a Alice 1 A cleaner\n"
        "t 202311011000 cleaner cleaner\n");
    Janusz(allocator);
    allocator.setSlotFirst();
    result = allocator.agents2TasksText();

    // alice gets the second clear job because, unlike Bob, she is in same group as Carol
    expected = "Carol does cleaner\nAlice does cleaner\n\nCost 2\n";
    if (expected != result)
        throw std::runtime_error(utname + " unit test failed");

    utname = "tid21-2";
    readstring(
        allocator,
        "a Carol 1 A cleaner\n"
        "a Alice 1 A cleaner\n"
        "t 202311011000 cleaner\n"
        "t 202312011000 cleaner\n");

    Janusz(allocator);
    allocator.setSlotNext();
    result = allocator.agents2TasksText();
    
    // alice gets the task in 2nd slot because she has the least previous workload
    expected = "Alice does cleaner\n\nCost 1\n";
    if (expected != result)
        throw std::runtime_error(utname + " unit test failed");
    allocator.setSlotFirst();

    utname = "tid21-3";
    readstring(
        allocator,
        "a Carol 1 A cleaner\n"
        "a Bob 1 B cleaner\n"
        "a Alice 1 A cleaner\n"
        "t 202311011000 cleaner cleaner\n");

    // give Alice a history of heavy workload
    allocator.getAgents()[2].setPreviousTasks( 10 );

    Janusz(allocator);
    result = allocator.agents2TasksText();
    
    // alice gets the task because 
    // although she has a greater previous workload than Bob
    // the family group gets priority over workload
    // https://github.com/JamesBremner/Agents2Tasks/issues/21#issuecomment-1813504598
    
    expected = "Carol does cleaner\nAlice does cleaner\n\nCost 2\n";
    if (expected != result)
        throw std::runtime_error(utname + " unit test failed");
    allocator.setSlotFirst();
```

**Comment by rejkid** [comment]
Passed with the input:
a alice 1 smith teacher 
a julia 1 smith teacher
a grace 1 walsh teacher
t 202311010830  teacher teacher

produced the result
a alice 1 smith teacher 
a julia 1 smith teacher 
a grace 1 walsh teacher 
t 202311010830  teacher teacher 
A 202311010830 alice to teacher
A 202311010830 julia to teacher

which is correct - the family (alice smith and julia smith) have been preferred over single family(walsh).
