### ISSUE TITLE
Assignments blocked for too long

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#23]
When an agent is assigned it should be blocked for two days - the assignment day and the following day. ( #8 )

They are being blocked for three days.

```
a alice 1 teacher 
t 202311010830 teacher 
t 202311020830 teacher 
t 202311031000 teacher 
t 202311041000 teacher 
A 202311010830 alice to teacher
A 202311041000 alice to teacher
```

Cause: the assignment timepoint is back-dated to the previous midnight.  This is correct, so that the blocking occurs on full days, not hours.  The bug is that the blocking test, because it uses the same code, also backdates to the previous midnight and thus needs an extra day to clear.

Fix:  check for just  24 hours between the two previous midnight timestamps.

```
a alice 1 teacher 
t 202311010830 teacher 
t 202311020830 teacher 
t 202311031000 teacher 
t 202311041000 teacher 
A 202311010830 alice to teacher
A 202311031000 alice to teacher
```

**Comment by rejkid** [comment]
Test passed with the input:
a alice 1 alice teacher 
t 202311010830  teacher 
t 202311020830  teacher 
t 202311031000  teacher 
t 202311041000  teacher 

producing output:
a alice 1 alice teacher 
t 202311010830  teacher 
t 202311020830  teacher 
t 202311031000  teacher 
t 202311041000  teacher 
A 202311010830 alice to teacher
A 202311031000 alice to teacher

Assignment is done for the 202311010830 and 202311031000 which is correct.
