### ISSUE TITLE
Different results from your build and mine.

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#24]
It looks solid good.
There is slight problem though with time slot "t 202311050830 Acolyte  MAS  Reader1 Reader2 EMHC".
Assignment look like that:

A 202311050830 rejkid@gmail.com&1998-06-07 to Reader2
A 202311050830 jblack@gmail.com&1961-03-24 to Acolyte
A 202311050830 rejkid@gmail.com&1992-08-28 to MAS
A 202311050830 rejkid@gmail.com&1961-07-02 to Reader1
A 202311050830 jwhite@gmail.com&1961-03-24 to EMHC

where Acolyte should be the agent "rejkid@gmail.com&1961-03-24" instead of "jblack@gmail.com&1961-03-24" because "rejkid@gmail.com&1961-03-24" agent is a family member of "rejkid@gmail.com" (other tasks are correctly filled in with the members of "rejkid@gmail.com").
The reason why agent "rejkid@gmail.com&1961-03-24" is not assigned to this time slot is because he is both an Acolyte and Cleaner and I had to put cleaner's group (A) in the place of family group, for it to participate in cleaners assignment.
This is what I was trying to explain to you yesterday. That is also why I was saying that we probably need another field to provide the cleaner information(A or B or C etc).
Can you see my problem? Maybe it can't be fixed I am not sure - it is getting very complex.

![a2tasks](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/a9fd872b-ebca-4764-93fe-b8ae24a22e9b)

![a2t](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/bac67b39-f4c3-4479-a586-f921f4a991e3)

[a2t_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/13384711/a2t_result.txt)

**Comment by JamesBremner** [comment]
I am getting different output for timeslot 202311050830

```
A 202311050830 jsmith@gmail.com&1961-03-24 to Reader2
A 202311050830 ismith@gmail.com&1961-07-02 to Acolyte
A 202311050830 mwalsh@gmail.com&2010-01-01 to MAS
A 202311050830 jblack@gmail.com&1961-03-24 to Reader1
A 202311050830 jwhite@gmail.com&1961-03-24 to EMHC
```

My complete output

[ex24r.txt](https://github.com/JamesBremner/Agents2Tasks/files/13384879/ex24r.txt)

**Comment by rejkid** [comment]
Strange. You are getting similar output I am describing for the time slot 202310290830.

**Comment by JamesBremner** [comment]
I have run the program twice and got the identical output both times.

**Comment by JamesBremner** [comment]
I have run the ex24.txt input through both the GUI and the console program: identical results.

**Comment by JamesBremner** [comment]
Please ensure you have built from the latest version of the code and that you could the same results when you run multiple times.

**Comment by rejkid** [comment]
I have just build the exe after pulling source code. I will do it again.
Could you please check the your output for the time slot 202310290830 - that is exactly the same problem I am describing - so it is there even in your output.

**Comment by JamesBremner** [comment]
> please check the your output for the time slot 202310290830 

OK.  What is the problem in that timeslot?

**Comment by rejkid** [comment]
Can you see my description of the problem  at the beginning of the issue please?

**Comment by JamesBremner** [comment]
We have different results in that timeslot also

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/a7eaf6db-4a2b-4700-9989-a3e20f581cb4)

**Comment by JamesBremner** [comment]
from your description

> Acolyte should be the agent "[rejkid@gmail.com](mailto:rejkid@gmail.com)&1961-03-24"

This IS the result you are getting ( though I get something different. )

**Comment by rejkid** [comment]
If you compare my time slot 202311050830 to yours 202310290830 - they are similar. Any way I am doing new build.

**Comment by rejkid** [comment]
James I am getting the same results as previously. If you look at my time slot 202311050830 you will see the problem I am describing in this issue. Your time slot 202310290830 is pretty much what I getting in my time slot.

**Comment by JamesBremner** [comment]
The important thing is to find out why we are getting different results.  If your build from the same code produces different results, then we are cannot check anything.

**Comment by rejkid** [comment]
Can you send me your exe or I can send you mine - it doesn't matter - that is probably good start.

**Comment by JamesBremner** [comment]
[Agents2TasksConsole13fa0875fe0c65f5fa3b4f10064474522617a56b.zip](https://github.com/JamesBremner/Agents2Tasks/files/13385516/Agents2TasksConsole13fa0875fe0c65f5fa3b4f10064474522617a56b.zip)

**Comment by rejkid** [comment]
Have you received my exe - if yes can you do a comparison too please?

**Comment by JamesBremner** [comment]
> Have you received my exe

No.

>  I compiled it using Visual Studio Code

Please post the build log.

Here is my build log

```
Executing task: C:\Users\James\code_ext\msys64\mingw64\bin\mingw32-make.exe -f .vscode/makefile console 

g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/console.o ./src/console.cpp -I./include -I../windex/include -I../raven-set
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/allocator.o ./src/allocator.cpp -I./include -I../windex/include -I../raven-set
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/cHungarian.o ./src/cHungarian.cpp -I./include -I../windex/include -I../raven-set
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/Janusz.o ./src/Janusz.cpp -I./include -I../windex/include -I../raven-set
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/unitTest.o ./src/unitTest.cpp -I./include -I../windex/include -I../raven-set
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/input.o ./src/input.cpp -I./include -I../windex/include -I../raven-set
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/cGraph.o ../PathFinder/src/cGraph.cpp -I./include -I../windex/include -I../raven-set
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/GraphTheory.o ../PathFinder/src/GraphTheory.cpp -I./include -I../windex/include -I../raven-set
g++ -g \
-o bin/Agents2TasksConsole.exe .vscode/obj/console.o .vscode/obj/allocator.o .vscode/obj/cHungarian.o .vscode/obj/Janusz.o .vscode/obj/unitTest.o .vscode/obj/input.o .vscode/obj/cGraph.o .vscode/obj/GraphTheory.o  \
-static-libstdc++ -static-libgcc -static -lComctl32 -lgdiplus -lgdi32 -lcomdlg32 -lstdc++fs

```

**Comment by rejkid** [comment]
Executing task: C:\MinGW\bin\mingw32-make.exe -f .vscode/makefile console 

g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/console.o ./src/console.cpp -I./include -I../windex/include -I../raven-set 
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/allocator.o ./src/allocator.cpp -I./include -I../windex/include -I../raven-set 
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/cHungarian.o ./src/cHungarian.cpp -I./include -I../windex/include -I../raven-set 
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/Janusz.o ./src/Janusz.cpp -I./include -I../windex/include -I../raven-set 
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/unitTest.o ./src/unitTest.cpp -I./include -I../windex/include -I../raven-set 
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/input.o ./src/input.cpp -I./include -I../windex/include -I../raven-set 
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/cGraph.o ../PathFinder/src/cGraph.cpp -I./include -I../windex/include -I../raven-set 
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/GraphTheory.o ../PathFinder/src/GraphTheory.cpp -I./include -I../windex/include -I../raven-set 
g++ -g \
-o bin/Agents2TasksConsole.exe .vscode/obj/console.o .vscode/obj/allocator.o .vscode/obj/cHungarian.o .vscode/obj/Janusz.o .vscode/obj/unitTest.o .vscode/obj/input.o .vscode/obj/cGraph.o .vscode/obj/GraphTheory.o  \
-static-libstdc++ -static-libgcc -static -lComctl32 -lgdiplus -lgdi32 -lcomdlg32 -lstdc++fs 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by JamesBremner** [comment]
It is too late to do anything more here tonight.

Tomorrow I will add some debug output which will hopefully give some hints to why our results are different.

**Comment by rejkid** [comment]
Which country are you from, just curious. In Aus it is almost 1 PM

**Comment by JamesBremner** [comment]
My github profile displays local time here.

**Comment by JamesBremner** [comment]
Here is my log file, input ex24

[a2tLog.zip](https://github.com/JamesBremner/Agents2Tasks/files/13393972/a2tLog.zip)

**Comment by rejkid** [comment]
I have pulled the "Agents2TasksConsole.exe" code and recompiled it. I compared assignment part and it is still different:

![Screenshot](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/30e3b42d-72b7-4743-8082-8db75daf05ad)

I have attached just in case my output file:
[a2t_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/13394356/a2t_result.txt)

**Comment by JamesBremner** [comment]
Please post the log file

**Comment by rejkid** [comment]
Here is my log file:
[a2tLog.txt](https://github.com/JamesBremner/Agents2Tasks/files/13394437/a2tLog.txt)

**Comment by JamesBremner** [comment]
You are using a different input file.

Please use ex24 in the repo.  https://github.com/JamesBremner/Agents2Tasks/blob/main/dat/ex24.txt

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/ab781f95-ed87-49af-b307-d93c9a7ef26b)

**Comment by rejkid** [comment]
Now they are the same. My testing is different then yours, because I am testing it from my GUI where input fille is regenerated every single time. Sorry I didn't realize it.

**Comment by JamesBremner** [comment]
Seems like this issue can be closed then.

**Comment by rejkid** [comment]
Yep. But it originated from the a different issue I reported at the start of this issue. Should I raise new issue for that?

**Comment by JamesBremner** [comment]
How many times do I need to explain that each 'github issue' should have discussion of just one project issue.  Why do you keep trying to confuse things by adding irrelevant stuff to old issues?

**Comment by JamesBremner** [comment]
> a different issue

When you find yourself typing these words: STOP and open a new issue.

**Comment by JamesBremner** [comment]
The threads that we create in each issue are intended to document the code that results.  There are links from the issue to the code and from the code to the issue.  

When an issue thread is laden with irrelevancy it becomes useless.

**Comment by JamesBremner** [comment]
>  My testing is different then yours, because I am testing it from my GUI 

Please do not do that.  There is no point in reporting on tests that I cannot reproduce.  

Run the console program from the command line using input files that we share in this repo.

**Comment by rejkid** [comment]
OK.
