### ISSUE TITLE
Incorrect assignment of family member

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#25]
There is slight problem with the time slot :
_"t 202310290830 Acolyte  MAS  Reader1 Reader2 EMHC EMHC"_.

Agent specification looks like this:
_a rejkid@gmail.com&1961-03-24 1 A Cleaner Acolyte_ 

Assignment part looks like that:
_A 202310290830 rejkid@gmail.com&1998-06-07 to Reader2
A 202310290830 jblack@gmail.com&1961-03-24 to Acolyte
A 202310290830 rejkid@gmail.com&1992-08-28 to MAS
A 202310290830 rejkid@gmail.com&1961-07-02 to Reader1
A 202310290830 jsmith@gmail.com&1961-03-24 to EMHC
A 202310290830 jwhite@gmail.com&1961-03-24 to EMHC_

The Acolyte (in Assignment part ) should be really the agent "rejkid@gmail.com&1961-03-24" instead of "jblack@gmail.com&1961-03-24" because "rejkid@gmail.com&1961-03-24" agent is a member of "rejkid@gmail.com" family  (other records for that slot are correctly filled in with the members of "rejkid@gmail.com" family).
I think the reason why agent "rejkid@gmail.com&1961-03-24" is not assigned to this time slot is because he is both an Acolyte and a Cleaner and I had to put cleaner's group (A) in the place of family group in agent specification, for it to participate in cleaners assignment.
This is why I was  saying that we probably need another field to provide the cleaner information(A or B or C etc) separately to family field.
Can you see my problem?  - it is getting very complex.

**Comment by JamesBremner** [comment]
> because "rejkid@gmail.com&1961-03-24" agent is a member of "rejkid@gmail.com" family

Are you using ex24?

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/39f19b7d-1420-4ac1-828e-afbd85e9d778)

**Comment by rejkid** [comment]
Yep. I am using ex24.txt. What I am saying is that I don't currently have any mechanism to mark "a rejkid@gmail.com&1961-03-24 1 A Cleaner Acolyte " record as belonging to  the family "rejkid@gmail.com" because I have to use letter "A" to indicate that the "rejkid@gmail.com&1961-03-24" is a cleaner. That is why I suggested to use two separate fields for family and cleaner. Maybe there is another solution.

**Comment by JamesBremner** [comment]
You wrote:

> the Acolyte (in Assignment part ) should be really the agent "[rejkid@gmail.com](mailto:rejkid@gmail.com)&1961-03-24" instead of "[jblack@gmail.com](mailto:jblack@gmail.com)&1961-03-24" because "[rejkid@gmail.com](mailto:rejkid@gmail.com)&1961-03-24" agent is a member of "[rejkid@gmail.com](mailto:rejkid@gmail.com)" family

This is simply wrong.  rejkid@gmail.com&1961-03-24 is a member of A family.

Are you reporting a bug?  Or are you requesting an enhancement?  Why won't you label your issues so I do not have to guess from the wording?

**Comment by rejkid** [comment]
Sorry. I am asking for an enhancement. The family to me is "rejkid@gmail.com" and "A" stands for a group of cleaners so "rejkid@gmail.com&1961-03-24" should participate in all family tasks but additionally he belongs to group "A" of cleaners.

**Comment by JamesBremner** [comment]
OK.  That is not at all clear from the way you wrote your first post in this issue.

Could you edit the first post so it is clear what you are asking for?  Then we can delete all the confused posts that followed.

**Comment by JamesBremner** [comment]
> There is slight problem with the time slot :

This look VERY MUCH like a bug report, doesn't it?

**Comment by rejkid** [comment]
OK.

**Comment by JamesBremner** [comment]
On second though, let's start fresh.  This issue is a hopeless mess.
