### ISSUE TITLE
Agent groups

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#27]
> A group is a set of agents working together on a particular task; in this case the "Cleaner" task.
> Groups perform their duties on a weekly basis (as per time slot assignments). For example, group "A" does cleaning on one Saturday, then group B does the following Saturday. 

As I showed ( in https://github.com/JamesBremner/Agents2Tasks/issues/26#issuecomment-1817218038 ) the current code handles cleaner groups as required, _so long as no cleaner capable agent has other capabilities in addition_.

For example in ex24 you have:

```
a rejkid@gmail.com&1961-03-24 1 A Cleaner Acolyte 
a ismith@gmail.com&1961-07-02 1 A Cleaner Acolyte 
```

The extra Acolyte capability messes up the cleaner group because if an agent is assigned to Acolyte then it will have an greater assignment count than the other group members, which means the group may be broken up when Saturday rolls around because of #5

We need to have an agent type called 'group agent'.

The group agent is specified as containing multiple ordinary agents.  The agents in a group MUST have the same capabilities as the group, but they MAY have additional capabilities.  An agent can only have membership of one group.  A group may have only one capability.

If a group agent is assigned to a task, then all the group members are assigned.  If a group member is assigned to a task, then the group that contains the agent is blocked.

Agents are specified to belong to a group by the new group specification.

| Field | Value | Description
|---|---|---|
0 | 'g' | identifies a line specifying a group
1 | string, no spaces | group task name
2 | space delimited list of strings | agents that belong to the group

For example here is the specs for a cleaner group agent:

```
a Alice 1 A 
a Bob 1 B 
a Carol 1 C Acolyte
g Cleaner Alice Bob Carol
```

**Comment by rejkid** [comment]
Hi James,
Sounds good. I just need to understand few things that are not clear to me right now.
>a Alice 1 A Cleaner
>a Bob 1 B Cleaner
>a Carol 1 C Cleaner Acolyte
>g Cleaner Alice Bob Carol     <= is this a group agent assignment?

Alice belongs to group A (or Family A), Bob to group B (or Family B) and Carol to group C (or Family C) - so they are coming from different groups, why are they part of same group agent? Is that a mistake? Every cleaner agent in my database has a string letter attached to it meaning which group he/she is belonging to.
When I am going to build agent group (in input file in my app) I would want to use that info from my DB.
Am I misunderstanding something here or that is all good?

Is the agent group going to have a name?

**Comment by JamesBremner** [comment]
> Alice belongs to group A (or Family A),

Do not confuse family and group.  

**Family**: An agent may be specified as a member of a family.  When possible agents in the same family will be assigned to the same timeslot.  Agents are specified to belong to a family using field 3 of the agent specification.  See https://github.com/JamesBremner/Agents2Tasks/wiki/File-format#agent-specification

**Group**: This is a new term, not yet implemented.  Agents are specified to belong to a group by the new group specification.

| Field | Value | Description
|---|---|---|
0 | 'g' | identifies a line specifying a group
1 | string, no spaces | group task name
2 | space delimited list of strings | agents that belong to the group

The agents in a group are assigned to a group task all together.  Groups are never broken up.

( Also, do not confuse specification and assignment.  Agents are specified to belong to a family and/or a group in the specification file read as input by the the A2T application.  Agents are assigned to tasks by the application. )

**Comment by rejkid** [comment]
1) In your example, group name is the name "Cleaner" (one of  the tasks)  - is this just coincidence?
2) Is group agent unique ?

3) Would the below example constitute a correctly defined  Agent/Group(s) specification?
a Alice 1 Smith Cleaner
a Bob 1 Walsh Cleaner
a Carol 1 White Cleaner Acolyte
g Cleaner Alice Bob Carol

a Janusz 1 Dalecki Cleaner
a George 1 Spinks Acolyte
a Virginia 1 Walsh Acolyte
g Cleaner Janusz
In which case does the group name follow agent specification?

Sorry James I am still trying to get my head around it.

**Comment by JamesBremner** [comment]
> In your example, group name is the name "Cleaner" (one of the tasks) - is this just coincidence?

That is the group task name.   Cleaner is the task to which a group must be assigned.

> Is group agent unique ?

Not sure what you mean by unique.  

There will be several groups that are able to be assigned to the cleaner group task.  Remember we are trying to implement

> A group is a set of agents working together on a particular task; in this case the "Cleaner" task.
> Groups perform their duties on a weekly basis (as per time slot assignments). For example, group "A" does cleaning on one Saturday, then group B does the following Saturday.

```
a Alice 1 Smith Cleaner
a Bob 1 Walsh Cleaner
a Carol 1 White Cleaner Acolyte
g Cleaner Alice Bob Carol
```

This is a correctly format group specification

**Comment by JamesBremner** [comment]
You raise a good point.  We need to have several groups that can be assigned to each group task ( otherwise there is no point in having this feature ) .  It will be good to easily distinguish between them ( so that you easily know which group has been assigned to each timeslot ).  I was thinking that the group members would be sufficient distinguish between groups.  However, that will be awkward to use.

**Comment by JamesBremner** [comment]
The simplest thing would be automatically name the group after the first member.  You might think of this as the group leader.

So the group

```
a Alice 1 Smith Cleaner
a Bob 1 Walsh Cleaner
a Carol 1 White Cleaner Acolyte
g Cleaner Alice Bob Carol
```

would be named `Alice-group`

But, if you prefer, we can add a field to the group agent specification where you specify your own unique group username.

**Comment by JamesBremner** [comment]
Here is the output with the agent group names for the leading agent.  Notice how the groups rotate over successive Saturdays.

```
a Alice 1 A Cleaner 
a Bob 1 B Cleaner 
a Carol 1 C Cleaner Acolyte 
a Janusz 1 Dalecki Cleaner 
a George 1 Spinks Acolyte 
a Virginia 1 Walsh Acolyte 
g Cleaner Janusz George Virginia
g Cleaner Alice Bob Carol
t 202311111000 Cleaner 
t 202311181000 Cleaner 
A 202311111000 Alice_group to Cleaner
A 202311111000 Alice in group Alice_group to Cleaner
A 202311111000 Bob in group Alice_group to Cleaner
A 202311111000 Carol in group Alice_group to Cleaner
A 202311181000 Janusz_group to Cleaner
A 202311181000 Janusz in group Janusz_group to Cleaner
A 202311181000 George in group Janusz_group to Cleaner
A 202311181000 Virginia in group Janusz_group to Cleaner

```

**Comment by rejkid** [comment]
Does group task name always be "Cleaner" ?

**Comment by rejkid** [comment]
In your example:
>a Alice 1 A Cleaner 
>a Bob 1 B Cleaner 
>a Carol 1 C Cleaner Acolyte 
>a Janusz 1 Dalecki Cleaner 
>a George 1 Spinks Acolyte 
>a Virginia 1 Walsh Acolyte 
>g Cleaner Janusz George Virginia
>g Cleaner Alice Bob Carol
>t 202311111000 Cleaner 
>t 202311181000 Cleaner 

Question is:
Why is George and Virginia in Cleaner group with Janusz when individually they are not assigned to Cleaner
or
Why does Janusz have task Cleaner assigned to him while George and Virginia don't but they are in Cleaner group with Janusz

**Comment by JamesBremner** [comment]
> Will group task name always be "Cleaner" ?

No.  The group task name is whatever you specify in field 1 of the group agent specification.  The complete description of the group agent specification is here https://github.com/JamesBremner/Agents2Tasks/issues/27#issuecomment-1817865832

**Comment by JamesBremner** [comment]
> Why is ...

Because I copied the example you posted in https://github.com/JamesBremner/Agents2Tasks/issues/27#issuecomment-1817900047

**Comment by rejkid** [comment]
Hi James,
I have prepared the code that produced this input file:
[a2t.txt](https://github.com/JamesBremner/Agents2Tasks/files/13412607/a2t.txt)

I have added additional field in group agent specification for my own unique group username (A/B/C etc) .
Could you run this through your current software to see what the initial output is and send it to me please?

**Comment by JamesBremner** [comment]
> I have added additional field in group agent specification for my own unique group username

That is a shame.  

It  makes things more complex with no benefit that I can see.  I will have to add code to read the extra field and to keep track of your names ( check for uniqueness and which names belong to agents and which belong groups )

> Could you run this through your current software

The current software does not implement group agents.  We have not yet agreed on the details.

**Comment by rejkid** [comment]
James, I am removing this extra field if it makes your life more difficult. Don't worry.

**Comment by JamesBremner** [comment]
from the specification file you posted

`t 202312051000 Cleaner Cleaner Cleaner Cleaner`

This is odd.  You want four cleaner groups assigned all to one timeslot?  No cleaner groups to any other slots.  Also, you have specified just three cleaner groups.

I thought you wanted to implement:

> Groups perform their duties on a weekly basis (as per time slot assignments). For example, group "A" does cleaning on one Saturday, then group B does the following Saturday.

**Comment by JamesBremner** [comment]
As you pointed out yesterday, there is confusion about whether or not the specification for a member of a group should include the group task.

For example

Should it be


```
a Carol 1 C Cleaner Acolyte
g Cleaner Alice Bob Carol
```

Or should it be

```
a Carol 1 C Acolyte
g Cleaner Alice Bob Carol
```

The second version is the simplest.

If you want to do the first version, then I can write code to ignore the group task capabilities of individual agents.

**Comment by rejkid** [comment]
4 cleaners is an error, sorry. But how do I specify I need 3 cleaners for the time slot?
> No cleaner groups to any other slots.
This is just an sample

**Comment by JamesBremner** [comment]
The number of agents in a group are specified in the 'g' line.

If you want groups with a different number of agents in them for different jobs, then you will have to specify different jobs

Like this

a Alice 1 A 
a Bob 1 B 
a Carol 1 C  Acolyte
a Derek 1 D
a Frank 1 F
g cleaner2 Alice Bob
g cleaner3 Carol Derek Frank
t 202311181000 cleaner2
t 202311251000 cleaner3

**Comment by JamesBremner** [comment]
In your file, you specify group members that do not exist.

For example

```
a rejkid@gmail.com&1961-03-24&A 1 rejkid@gmail.com Cleaner Acolyte 
g Cleaner rejkid@gmail.com&1961-03-24 ...
```

You must ensure that agent names are consistent.  It would help a lot if you used simpler agent names.  I suggest you use the ROWID of the agent in your database.

**Comment by rejkid** [comment]
Can we agree on this format:

a mwalsh@gmail.com&2010-01-01 1 mwalsh@gmail.com MAS 
a asmith@gmail.com&1998-06-07 1 asmith@gmail.com 
a rejkid@gmail.com&1961-03-24 1 rejkid@gmail.com Acolyte 
a jblack@gmail.com&1961-03-24 1 jblack@gmail.com EMHC Reader1 Acolyte 
a ismith@gmail.com&1961-07-02 1 ismith@gmail.com Acolyte 
a iblack@gmail.com&1961-07-02 1 iblack@gmail.com 
a jsmith@gmail.com&1961-03-24 1 jsmith@gmail.com EMHC Reader2 
a ablack@gmail.com&1998-06-07 1 ablack@gmail.com 
a jwhite@gmail.com&1961-03-24 1 jwhite@gmail.com EMHC Reader1 
a rejkid@gmail.com&1992-08-28 1 rejkid@gmail.com MAS 
a rejkid@gmail.com&1998-06-07 1 rejkid@gmail.com Reader2 
a rejkid@gmail.com&1961-07-02 1 rejkid@gmail.com Reader1 
a iwhite@gmail.com&1961-07-02 1 iwhite@gmail.com 
a awhite@gmail.com&1998-06-07 1 awhite@gmail.com 
a osiekkolawy@gmail.com&1961-03-24 1 osiekkolawy@gmail.com MAS 
g Cleaner mwalsh@gmail.com&2010-01-01 
g Cleaner asmith@gmail.com&1998-06-07  rejkid@gmail.com&1961-03-24  ismith@gmail.com&1961-07-02 
g Cleaner iblack@gmail.com&1961-07-02  ablack@gmail.com&1998-06-07  iwhite@gmail.com&1961-07-02  awhite@gmail.com&1998-06-07 

t 202310220830 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC 
t 202310221000 Acolyte  MAS MAS Reader1 Reader2 EMHC  
t 202310290830 Acolyte  MAS  Reader1 Reader2 EMHC EMHC 
t 202310291000 Acolyte  MAS  Reader1 Reader2  EMHC 
t 202311050830 Acolyte  MAS  Reader1 Reader2 EMHC  
t 202311051000 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC 
t 202312051000 Cleaner
t 202312121000 Cleaner

I would like to keep in user name an e-mail and DOB - that helps me create schedules from the output.

**Comment by JamesBremner** [comment]
Looks good.  It conforms to the specification format I proposed at https://github.com/JamesBremner/Agents2Tasks/issues/27?notification_referrer_id=NT_kwDOAB85E7I4NDY0MTU2MDA1OjIwNDYyMjc#issuecomment-1817865832

**Comment by JamesBremner** [comment]
> I would like to keep in user name an e-mail and DOB - that helps me to create schedules from the output.

OK.

However, I am curious as to why you want to use this complicated, even messy system.  If you used the ROWID from your database for the agent name, then you could get whatever info you need simply and efficiently directly from the database instead of parsing the a2t output.

**Comment by rejkid** [comment]
I am not familiar with the ROWID  - I just don't want to experiment with it right now - is that OK?

**Comment by JamesBremner** [comment]
Sure.

Using ROWID is the most efficient way to get data from a database.

**Comment by rejkid** [comment]
Hi James,
If we don't have any more potential problems to clarify I will close this issue -?

**Comment by JamesBremner** [comment]
Now that we have agreed on the the feature requirements, it needs to be implemented.

**Comment by JamesBremner** [comment]
```
a mwalsh@gmail.com&2010-01-01 1 mwalsh@gmail.com MAS
a asmith@gmail.com&1998-06-07 1 asmith@gmail.com none
a rejkid@gmail.com&1961-03-24 1 rejkid@gmail.com Acolyte
a jblack@gmail.com&1961-03-24 1 jblack@gmail.com EMHC Reader1 Acolyte
a ismith@gmail.com&1961-07-02 1 ismith@gmail.com Acolyte
a iblack@gmail.com&1961-07-02 1 iblack@gmail.com none
a jsmith@gmail.com&1961-03-24 1 jsmith@gmail.com EMHC Reader2
a ablack@gmail.com&1998-06-07 1 ablack@gmail.com none
a jwhite@gmail.com&1961-03-24 1 jwhite@gmail.com EMHC Reader1
a rejkid@gmail.com&1992-08-28 1 rejkid@gmail.com MAS
a rejkid@gmail.com&1998-06-07 1 rejkid@gmail.com Reader2
a rejkid@gmail.com&1961-07-02 1 rejkid@gmail.com Reader1
a iwhite@gmail.com&1961-07-02 1 iwhite@gmail.com none
a awhite@gmail.com&1998-06-07 1 awhite@gmail.com none
a osiekkolawy@gmail.com&1961-03-24 1 osiekkolawy@gmail.com MAS
g mwalsh@gmail.com&2010-01-01_group mwalsh@gmail.com&2010-01-01
g asmith@gmail.com&1998-06-07_group asmith@gmail.com&1998-06-07 rejkid@gmail.com&1961-03-24 ismith@gmail.com&1961-07-02
g iblack@gmail.com&1961-07-02_group iblack@gmail.com&1961-07-02 ablack@gmail.com&1998-06-07 iwhite@gmail.com&1961-07-02 awhite@gmail.com&1998-06-07
t 202310220830 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC
t 202310221000 Acolyte MAS MAS Reader1 Reader2 EMHC
t 202310290830 Acolyte MAS Reader1 Reader2 EMHC EMHC
t 202310291000 Acolyte MAS Reader1 Reader2 EMHC
t 202311050830 Acolyte MAS Reader1 Reader2 EMHC
t 202311051000 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC
t 202312051000 Cleaner
t 202312121000 Cleaner
mwalsh@gmail.com&2010-01-01_group to Acolyte
mwalsh@gmail.com&2010-01-01 in mwalsh@gmail.com&2010-01-01_group to Acolyte
iblack@gmail.com&1961-07-02_group to Acolyte
iblack@gmail.com&1961-07-02 in iblack@gmail.com&1961-07-02_group to Acolyte
ablack@gmail.com&1998-06-07 in iblack@gmail.com&1961-07-02_group to Acolyte
iwhite@gmail.com&1961-07-02 in iblack@gmail.com&1961-07-02_group to Acolyte
awhite@gmail.com&1998-06-07 in iblack@gmail.com&1961-07-02_group to Acolyte
asmith@gmail.com&1998-06-07_group to MAS
asmith@gmail.com&1998-06-07 in asmith@gmail.com&1998-06-07_group to MAS
rejkid@gmail.com&1961-03-24 in asmith@gmail.com&1998-06-07_group to MAS
ismith@gmail.com&1961-07-02 in asmith@gmail.com&1998-06-07_group to MAS
rejkid@gmail.com&1961-07-02 to MAS
rejkid@gmail.com&1992-08-28 to Reader1
rejkid@gmail.com&1998-06-07 to Reader2
jblack@gmail.com&1961-03-24 to EMHC
jsmith@gmail.com&1961-03-24 to EMHC
jwhite@gmail.com&1961-03-24 to Acolyte
osiekkolawy@gmail.com&1961-03-24 to MAS
asmith@gmail.com&1998-06-07_group to Acolyte
asmith@gmail.com&1998-06-07 in asmith@gmail.com&1998-06-07_group to Acolyte
rejkid@gmail.com&1961-03-24 in asmith@gmail.com&1998-06-07_group to Acolyte
ismith@gmail.com&1961-07-02 in asmith@gmail.com&1998-06-07_group to Acolyte
iblack@gmail.com&1961-07-02_group to MAS
iblack@gmail.com&1961-07-02 in iblack@gmail.com&1961-07-02_group to MAS
ablack@gmail.com&1998-06-07 in iblack@gmail.com&1961-07-02_group to MAS
iwhite@gmail.com&1961-07-02 in iblack@gmail.com&1961-07-02_group to MAS
awhite@gmail.com&1998-06-07 in iblack@gmail.com&1961-07-02_group to MAS
mwalsh@gmail.com&2010-01-01_group to Reader1
mwalsh@gmail.com&2010-01-01 in mwalsh@gmail.com&2010-01-01_group to Reader1
rejkid@gmail.com&1998-06-07 to Reader2
rejkid@gmail.com&1992-08-28 to EMHC
rejkid@gmail.com&1961-07-02 to EMHC
jwhite@gmail.com&1961-03-24 to Acolyte
osiekkolawy@gmail.com&1961-03-24 to MAS
jblack@gmail.com&1961-03-24 to Reader1
jsmith@gmail.com&1961-03-24 to Reader2
mwalsh@gmail.com&2010-01-01_group to Acolyte
mwalsh@gmail.com&2010-01-01 in mwalsh@gmail.com&2010-01-01_group to Acolyte
iblack@gmail.com&1961-07-02_group to MAS
iblack@gmail.com&1961-07-02 in iblack@gmail.com&1961-07-02_group to MAS
ablack@gmail.com&1998-06-07 in iblack@gmail.com&1961-07-02_group to MAS
iwhite@gmail.com&1961-07-02 in iblack@gmail.com&1961-07-02_group to MAS
awhite@gmail.com&1998-06-07 in iblack@gmail.com&1961-07-02_group to MAS
asmith@gmail.com&1998-06-07_group to Reader1
asmith@gmail.com&1998-06-07 in asmith@gmail.com&1998-06-07_group to Reader1
rejkid@gmail.com&1961-03-24 in asmith@gmail.com&1998-06-07_group to Reader1
ismith@gmail.com&1961-07-02 in asmith@gmail.com&1998-06-07_group to Reader1
rejkid@gmail.com&1961-07-02 to Reader2
rejkid@gmail.com&1992-08-28 to EMHC
rejkid@gmail.com&1998-06-07 to Acolyte
jsmith@gmail.com&1961-03-24 to Acolyte
osiekkolawy@gmail.com&1961-03-24 to MAS
jwhite@gmail.com&1961-03-24 to MAS
jblack@gmail.com&1961-03-24 to Reader1
iblack@gmail.com&1961-07-02_group to Cleaner
iblack@gmail.com&1961-07-02 in iblack@gmail.com&1961-07-02_group to Cleaner
ablack@gmail.com&1998-06-07 in iblack@gmail.com&1961-07-02_group to Cleaner
iwhite@gmail.com&1961-07-02 in iblack@gmail.com&1961-07-02_group to Cleaner
awhite@gmail.com&1998-06-07 in iblack@gmail.com&1961-07-02_group to Cleaner
mwalsh@gmail.com&2010-01-01_group to Cleaner
mwalsh@gmail.com&2010-01-01 in mwalsh@gmail.com&2010-01-01_group to Cleaner
```

**Comment by JamesBremner** [comment]
Updated file format specification https://github.com/JamesBremner/Agents2Tasks/wiki/File-format

**Comment by rejkid** [comment]
Documentation looks good. File format attached to this issue conforms to the specification format. The issue can be closed.
