### ISSUE TITLE
Unit test fails when run from a command prompt

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#29]
Does Agents2Tasks.exe replace Agents2TasksConsole.exe
I can't see the target in makefile to build console app

**Comment by JamesBremner** [comment]
Yes

**Comment by rejkid** [comment]
I am getting this output with the input ex27j.txt

C:\ScheduleMeWorkspace\ScheduleMeBackEnd>C:\ScheduleMeWorkspace\ScheduleMeBackEnd\Agents2Tasks.exe  ./Upload/ex27j.txt ./Upload/a2t_result.txt
terminate called after throwing an instance of 'std::runtime_error'
  what():  16 1 unit test failed

**Comment by JamesBremner** [comment]
Here is the unit test code

https://github.com/JamesBremner/Agents2Tasks/blob/bf2585c7989b511f2aeb7d0d00e8ad343e8d5cc9/src/unitTest.cpp#L11-L34

Run under the debugger and see what the difference between expected and result is

**Comment by rejkid** [comment]
#
![image](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/b883c74a-1f50-4b04-84a7-0fd951b4a543)

**Comment by JamesBremner** [comment]
You need to show the history

**Comment by rejkid** [comment]
![image](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/f3bcf77b-8931-4df1-9674-a8d42b2d545d)

**Comment by JamesBremner** [comment]
That looks good.

What do you get from the debugger?

**Comment by JamesBremner** [comment]
You should also post the complete build log.

 Executing task: C:\Users\James\code_ext\msys64\mingw64\bin\mingw32-make.exe -f .vscode/makefile a2t 

```
g++ ./src/main.cpp  \
-c -o .vscode/obj/main.o  -I./include -I../raven-set  -std=c++17 -g -D_mingw_
g++ ./src/input.cpp  \
-c -o .vscode/obj/input.o  -I./include -I../raven-set  -std=c++17 -g -D_mingw_
g++ ./src/cAgent.cpp  \
-c -o .vscode/obj/cAgent.o  -I./include -I../raven-set  -std=c++17 -g -D_mingw_
g++ ./src/cTask.cpp  \
-c -o .vscode/obj/cTask.o  -I./include -I../raven-set  -std=c++17 -g -D_mingw_
g++ ./src/cSlot.cpp  \
-c -o .vscode/obj/cSlot.o  -I./include -I../raven-set  -std=c++17 -g -D_mingw_
g++ ./src/cAssign.cpp  \
-c -o .vscode/obj/cAssign.o  -I./include -I../raven-set  -std=c++17 -g -D_mingw_
g++ ./src/unitTest.cpp  \
-c -o .vscode/obj/unitTest.o  -I./include -I../raven-set  -std=c++17 -g -D_mingw_
g++ -g \
-o bin/Agents2Tasks.exe .vscode/obj/main.o .vscode/obj/input.o .vscode/obj/cAgent.o .vscode/obj/cTask.o .vscode/obj/cSlot.o .vscode/obj/cAssign.o .vscode/obj/unitTest.o  \
-static-libstdc++ -static-libgcc -static -lComctl32 -lgdiplus -lgdi32 -lcomdlg32 -lstdc++fs
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by JamesBremner** [comment]
I can reproduce this!

**Comment by rejkid** [comment]
I don't know how to run debugger for cpp in VC. I have never done it before

**Comment by JamesBremner** [comment]
Press key F5 to run under debugger

**Comment by rejkid** [comment]
I did and I get this dialog box:
![image](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/622be0c9-57b4-4d4b-acef-a19bc3d827f4)
... I pressed "Install cppdbg Extension" and it says "No extension found"

**Comment by JamesBremner** [comment]
You will have to ask a VSCODE forum about that

**Comment by JamesBremner** [comment]
Cause: `std::stable_sort()` appears not to be working as expected.  It seems that the order of equivalent agents is not stable, but random.

**Comment by rejkid** [comment]
is it fixable ?

**Comment by JamesBremner** [comment]
I have labelled this issue 'accepted'  That means I am working on it.  You can find the meaning of any label by hovering the mouse cursor over the label.

**Comment by rejkid** [comment]
The Agents2Tasks.exe is passing all unit tests for input file ex27j.txt and generates the output file.
