### ISSUE TITLE
Assignment display shows one timeslot at a time

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#3]
Currently, the assignment display shows the results for all timeslots.  This works for small test problems, but will be useless for large real world problems with many timeslots and tasks.

The display should show the assignments for one timeslot at a time and provide means to navigate between the timeslots in the problem.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/2ba2d39e-b9ba-46ac-88d8-05945339079a)

**Comment by JamesBremner** [comment]
@rejkid This issue is assigned to you in test.

This means that I would like you to build and test this.  If you are happy with it, then please close it.  If you find a problem with it, then post a complete test report ( remember I cannot see over you shoulder! ) and assign this issue back to me.

If, while testing, you find a problem with something else, then open a new issue describing the problem and assign the new issue to me.

**Comment by rejkid** [comment]
James, where is specification for file input format? I am little bit lost here what do you want me to do?

**Comment by JamesBremner** [comment]
The readme is shown at https://github.com/JamesBremner/Agents2Tasks

There is a link from there to the wiki describing the input file format

**Comment by rejkid** [comment]
[example_output.txt](https://github.com/JamesBremner/Agents2Tasks/files/13275708/example_output.txt)

I have attached the file that contains input and output together.
The issue that I see is that the output is missing Steven and Andrew agens who can be an accountant or teacher.
This is true for both F and H algorithms.
Am I doing something wrong or this is how the algorithm works.

**Comment by JamesBremner** [comment]
Please remember to read the title of an an issue.  Do not post questions to issues that are about something else.

I have opened a new issue ( #5 ) for your question about extra agents.

Please read my post explaining how to handle test issues  https://github.com/JamesBremner/Agents2Tasks/issues/3#issuecomment-1793775428

In particular, do not assign test issues to me until you have tested them and posted your test report.

**Comment by JamesBremner** [comment]
@rejkid  This issue was assigned to you in test three days ago.  Why is it taking so long?

**Comment by rejkid** [comment]
I have tested with the configuration attached. The test has passed. Input and Result files attached.

[assign_disp.txt](https://github.com/JamesBremner/Agents2Tasks/files/13308656/assign_disp.txt)
[assign_disp_res.txt](https://github.com/JamesBremner/Agents2Tasks/files/13308657/assign_disp_res.txt)
