### ISSUE TITLE
Group is assigned to task it cannot do

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#31]
```
g Cleaner asmith@gmail.com&1998-06-07 rejkid@gmail.com&1961-03-24 ismith@gmail.com&1961-07-02
...
A 202310220830 asmith@gmail.com&1998-06-07_group to Acolyte
A 202310220830 asmith@gmail.com&1998-06-07 in asmith@gmail.com&1998-06-07_group to Acolyte
A 202310220830 rejkid@gmail.com&1961-03-24 in asmith@gmail.com&1998-06-07_group to Acolyte
A 202310220830 ismith@gmail.com&1961-07-02 in asmith@gmail.com&1998-06-07_group to Acolyte
```

**Comment by JamesBremner** [comment]
1.  This seems to be a bug.  I will open a separate issue for it.

2.  Groups are assigned as a whole, they are not broken up.

**Comment by rejkid** [comment]
>Groups are assigned as a whole, they are not broken up

But Acolytes are not assigned to any group. I just specified that I need 2 Acolytes for this time slot 202310220830 and expected just 2acolytes, but there are 4.  Do i misunderstand something?

**Comment by JamesBremner** [comment]
> But Acolytes are not assigned to any group.

You mean no group is specified to be able to do the acolyte task.  ( The input file specifies what tasks agent can do, the app does the actual assigning )

**Comment by rejkid** [comment]
So how do I specify that I only need two Acolytes for that timeslot?

**Comment by JamesBremner** [comment]
This is a bug, assigned to me.

I will work on it tomorrow.

Please pay attention to the issue assigning and labelling.  If an issue is not assigned to you, then you do not need to do anything until it IS assigned to you.

**Comment by JamesBremner** [comment]
Cause: missing findAgentsForTask() method

**Comment by rejkid** [comment]
Tested with input file "ex27j.txt" from repository.
There are no records assigned to task it can't do:
A 202310220830 asmith@gmail.com&1998-06-07_group to Acolyte - those records don't appear in the output result file anymore.
