### ISSUE TITLE
Document "File format" enhancement

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#33]
Should we mention in the document "File format" in section "Assignments" for "Output line for agent assigned as part of a group" that the "group agent name" is suffixed with the word "_group" ?

**Comment by JamesBremner** [comment]
> the "group agent name" is suffixed with the word "_group" ?

The group agent name is the name of the lead agent sufficed with "_group"

**Comment by rejkid** [comment]
Agreed

**Comment by rejkid** [comment]
Happy with the change.
