### ISSUE TITLE
Workload sharing not working for groups

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#34]
Assignment for time slot 202312121000 should use next Cleaner group iblack@gmail.com&1961-07-02_group instead of re-using previous asmith@gmail.com&1998-06-07_group group.

**Comment by JamesBremner** [comment]
It would be so much easier if you included the entire output that you are getting

Here is my output from ex27j.  Note that in my output `[asmith@gmail.com](mailto:asmith@gmail.com)&1998-06-07_group` is assigned just once.  No re-using of a group occurs. 

```
a mwalsh@gmail.com&2010-01-01 1 mwalsh@gmail.com MAS
a asmith@gmail.com&1998-06-07 1 asmith@gmail.com none
a rejkid@gmail.com&1961-03-24 1 rejkid@gmail.com Acolyte
a jblack@gmail.com&1961-03-24 1 jblack@gmail.com EMHC Reader1 Acolyte
a ismith@gmail.com&1961-07-02 1 ismith@gmail.com Acolyte
a iblack@gmail.com&1961-07-02 1 iblack@gmail.com none
a jsmith@gmail.com&1961-03-24 1 jsmith@gmail.com EMHC Reader2
a ablack@gmail.com&1998-06-07 1 ablack@gmail.com none
a jwhite@gmail.com&1961-03-24 1 jwhite@gmail.com EMHC Reader1
a rejkid@gmail.com&1992-08-28 1 rejkid@gmail.com MAS
a rejkid@gmail.com&1998-06-07 1 rejkid@gmail.com Reader2
a rejkid@gmail.com&1961-07-02 1 rejkid@gmail.com Reader1
a iwhite@gmail.com&1961-07-02 1 iwhite@gmail.com none
a awhite@gmail.com&1998-06-07 1 awhite@gmail.com none
a osiekkolawy@gmail.com&1961-03-24 1 osiekkolawy@gmail.com MAS
g Cleaner mwalsh@gmail.com&2010-01-01
g Cleaner asmith@gmail.com&1998-06-07 rejkid@gmail.com&1961-03-24 ismith@gmail.com&1961-07-02
g Cleaner iblack@gmail.com&1961-07-02 ablack@gmail.com&1998-06-07 iwhite@gmail.com&1961-07-02 awhite@gmail.com&1998-06-07
t 202310220830 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC
t 202310221000 Acolyte MAS MAS Reader1 Reader2 EMHC
t 202310290830 Acolyte MAS Reader1 Reader2 EMHC EMHC
t 202310291000 Acolyte MAS Reader1 Reader2 EMHC
t 202311050830 Acolyte MAS Reader1 Reader2 EMHC
t 202311051000 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC
t 202312051000 Cleaner
t 202312121000 Cleaner
A 202310220830 rejkid@gmail.com&1961-03-24 to Acolyte
A 202310220830 jblack@gmail.com&1961-03-24 to Acolyte
A 202310220830 rejkid@gmail.com&1992-08-28 to MAS
A 202310220830 mwalsh@gmail.com&2010-01-01 to MAS
A 202310220830 rejkid@gmail.com&1961-07-02 to Reader1
A 202310220830 rejkid@gmail.com&1998-06-07 to Reader2
A 202310220830 jsmith@gmail.com&1961-03-24 to EMHC
A 202310220830 jwhite@gmail.com&1961-03-24 to EMHC
A 202310221000 ismith@gmail.com&1961-07-02 to Acolyte
A 202310221000 osiekkolawy@gmail.com&1961-03-24 to MAS
A 202310290830 ismith@gmail.com&1961-07-02 to Acolyte
A 202310290830 osiekkolawy@gmail.com&1961-03-24 to MAS
A 202310290830 rejkid@gmail.com&1961-07-02 to Reader1
A 202310290830 rejkid@gmail.com&1998-06-07 to Reader2
A 202310290830 jblack@gmail.com&1961-03-24 to EMHC
A 202310290830 jsmith@gmail.com&1961-03-24 to EMHC
A 202310291000 rejkid@gmail.com&1961-03-24 to Acolyte
A 202310291000 rejkid@gmail.com&1992-08-28 to MAS
A 202310291000 jwhite@gmail.com&1961-03-24 to Reader1
A 202311050830 rejkid@gmail.com&1961-03-24 to Acolyte
A 202311050830 rejkid@gmail.com&1992-08-28 to MAS
A 202311050830 rejkid@gmail.com&1961-07-02 to Reader1
A 202311050830 rejkid@gmail.com&1998-06-07 to Reader2
A 202311050830 jwhite@gmail.com&1961-03-24 to EMHC
A 202311051000 ismith@gmail.com&1961-07-02 to Acolyte
A 202311051000 jblack@gmail.com&1961-03-24 to Acolyte
A 202311051000 mwalsh@gmail.com&2010-01-01 to MAS
A 202311051000 osiekkolawy@gmail.com&1961-03-24 to MAS
A 202311051000 jsmith@gmail.com&1961-03-24 to Reader2
A 202312051000 mwalsh@gmail.com&2010-01-01_group to Cleaner
A 202312051000 mwalsh@gmail.com&2010-01-01 in mwalsh@gmail.com&2010-01-01_group to Cleaner
A 202312121000 asmith@gmail.com&1998-06-07_group to Cleaner
A 202312121000 asmith@gmail.com&1998-06-07 in asmith@gmail.com&1998-06-07_group to Cleaner
A 202312121000 rejkid@gmail.com&1961-03-24 in asmith@gmail.com&1998-06-07_group to Cleaner
A 202312121000 ismith@gmail.com&1961-07-02 in asmith@gmail.com&1998-06-07_group to Cleaner
```

**Comment by rejkid** [comment]
Sorry. This is my output. Shouldn't they be the same? The end of file is different.
Here is my output from ex27j.

a mwalsh@gmail.com&2010-01-01 1 mwalsh@gmail.com MAS
a asmith@gmail.com&1998-06-07 1 asmith@gmail.com none
a rejkid@gmail.com&1961-03-24 1 rejkid@gmail.com Acolyte
a jblack@gmail.com&1961-03-24 1 jblack@gmail.com EMHC Reader1 Acolyte
a ismith@gmail.com&1961-07-02 1 ismith@gmail.com Acolyte
a iblack@gmail.com&1961-07-02 1 iblack@gmail.com none
a jsmith@gmail.com&1961-03-24 1 jsmith@gmail.com EMHC Reader2
a ablack@gmail.com&1998-06-07 1 ablack@gmail.com none
a jwhite@gmail.com&1961-03-24 1 jwhite@gmail.com EMHC Reader1
a rejkid@gmail.com&1992-08-28 1 rejkid@gmail.com MAS
a rejkid@gmail.com&1998-06-07 1 rejkid@gmail.com Reader2
a rejkid@gmail.com&1961-07-02 1 rejkid@gmail.com Reader1
a iwhite@gmail.com&1961-07-02 1 iwhite@gmail.com none
a awhite@gmail.com&1998-06-07 1 awhite@gmail.com none
a osiekkolawy@gmail.com&1961-03-24 1 osiekkolawy@gmail.com MAS
g Cleaner mwalsh@gmail.com&2010-01-01
g Cleaner asmith@gmail.com&1998-06-07 rejkid@gmail.com&1961-03-24 ismith@gmail.com&1961-07-02
g Cleaner iblack@gmail.com&1961-07-02 ablack@gmail.com&1998-06-07 iwhite@gmail.com&1961-07-02 awhite@gmail.com&1998-06-07
t 202310220830 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC
t 202310221000 Acolyte MAS MAS Reader1 Reader2 EMHC
t 202310290830 Acolyte MAS Reader1 Reader2 EMHC EMHC
t 202310291000 Acolyte MAS Reader1 Reader2 EMHC
t 202311050830 Acolyte MAS Reader1 Reader2 EMHC
t 202311051000 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC
t 202312051000 Cleaner
t 202312121000 Cleaner
A 202310220830 rejkid@gmail.com&1961-03-24 to Acolyte
A 202310220830 jblack@gmail.com&1961-03-24 to Acolyte
A 202310220830 rejkid@gmail.com&1992-08-28 to MAS
A 202310220830 mwalsh@gmail.com&2010-01-01 to MAS
A 202310220830 rejkid@gmail.com&1961-07-02 to Reader1
A 202310220830 rejkid@gmail.com&1998-06-07 to Reader2
A 202310220830 jsmith@gmail.com&1961-03-24 to EMHC
A 202310220830 jwhite@gmail.com&1961-03-24 to EMHC
A 202310221000 ismith@gmail.com&1961-07-02 to Acolyte
A 202310221000 osiekkolawy@gmail.com&1961-03-24 to MAS
A 202310290830 ismith@gmail.com&1961-07-02 to Acolyte
A 202310290830 osiekkolawy@gmail.com&1961-03-24 to MAS
A 202310290830 rejkid@gmail.com&1961-07-02 to Reader1
A 202310290830 rejkid@gmail.com&1998-06-07 to Reader2
A 202310290830 jblack@gmail.com&1961-03-24 to EMHC
A 202310290830 jsmith@gmail.com&1961-03-24 to EMHC
A 202310291000 rejkid@gmail.com&1961-03-24 to Acolyte
A 202310291000 rejkid@gmail.com&1992-08-28 to MAS
A 202310291000 jwhite@gmail.com&1961-03-24 to Reader1
A 202311050830 rejkid@gmail.com&1961-03-24 to Acolyte
A 202311050830 rejkid@gmail.com&1992-08-28 to MAS
A 202311050830 rejkid@gmail.com&1961-07-02 to Reader1
A 202311050830 rejkid@gmail.com&1998-06-07 to Reader2
A 202311050830 jwhite@gmail.com&1961-03-24 to EMHC
A 202311051000 ismith@gmail.com&1961-07-02 to Acolyte
A 202311051000 jblack@gmail.com&1961-03-24 to Acolyte
A 202311051000 mwalsh@gmail.com&2010-01-01 to MAS
A 202311051000 osiekkolawy@gmail.com&1961-03-24 to MAS
A 202311051000 jsmith@gmail.com&1961-03-24 to Reader2
A 202312051000 asmith@gmail.com&1998-06-07_group to Cleaner
A 202312051000 asmith@gmail.com&1998-06-07 in asmith@gmail.com&1998-06-07_group to Cleaner
A 202312051000 rejkid@gmail.com&1961-03-24 in asmith@gmail.com&1998-06-07_group to Cleaner
A 202312051000 ismith@gmail.com&1961-07-02 in asmith@gmail.com&1998-06-07_group to Cleaner
A 202312121000 asmith@gmail.com&1998-06-07_group to Cleaner
A 202312121000 asmith@gmail.com&1998-06-07 in asmith@gmail.com&1998-06-07_group to Cleaner
A 202312121000 rejkid@gmail.com&1961-03-24 in asmith@gmail.com&1998-06-07_group to Cleaner
A 202312121000 ismith@gmail.com&1961-07-02 in asmith@gmail.com&1998-06-07_group to Cleaner

![image](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/f6d9bd87-6c8a-45eb-8280-10830ad7c009)

**Comment by JamesBremner** [comment]
They _should_ be the same because the specifications are the same.

It looks to me like there is a problem with the even workload feature for groups.

Here is a simpler test file that shows the problem without so much irrelevant details

[ex34-2.txt](https://github.com/JamesBremner/Agents2Tasks/files/13461865/ex34-2.txt)

**Comment by JamesBremner** [comment]
And here is an even simpler file that shows the same problem without all the gibberish that makes it hard to see what is happening

[ex34-3.txt](https://github.com/JamesBremner/Agents2Tasks/files/13461900/ex34-3.txt)

This outputs

```
a mwalsh 1 mwalsh MAS
a asmith 1 asmith none
a rejkid1 1 rejkid Acolyte
a jblack 1 jblack EMHC Reader1 Acolyte
a ismith 1 ismith Acolyte
a iblack 1 iblack none
a jsmith 1 jsmith EMHC Reader2
a ablack 1 ablack none
a jwhite 1 jwhite EMHC Reader1
a iwhite 1 iwhite none
a awhite 1 awhite none
g Cleaner asmith rejkid1 ismith
g Cleaner iblack ablack iwhite awhite
t 202312051000 Cleaner
t 202312121000 Cleaner
A 202312051000 asmith_group to Cleaner
A 202312051000 asmith in asmith_group to Cleaner
A 202312051000 rejkid1 in asmith_group to Cleaner
A 202312051000 ismith in asmith_group to Cleaner
A 202312121000 asmith_group to Cleaner
A 202312121000 asmith in asmith_group to Cleaner
A 202312121000 rejkid1 in asmith_group to Cleaner
A 202312121000 ismith in asmith_group to Cleaner
```

**Comment by JamesBremner** [comment]
Cause: cAgentGroup not initializing assigned count

**Comment by rejkid** [comment]
[a2t.txt](https://github.com/JamesBremner/Agents2Tasks/files/13462224/a2t.txt)
[a2t_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/13462225/a2t_result.txt)
 Tested with 3 Cleaner groups, a2t.txt as an input and a2t_result.txt as an output. Assignment is correct -  all three groups have been used in turn.
