### ISSUE TITLE
Workload sharing fails when timeslots exceed agents

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#35]
There is problem when the number of time slots for Cleaners is greater then the number of Cleaner task groups.
When the last Cleaner group is used ("mwalsh@gmail.com&2010-01-01_group"), the app instead of starting assigning with the 
first group ("ablack@gmail.com&1998-06-07_group") it starts going backword such that the last group is used again ("mwalsh@gmail.com&2010-01-01_group").
It should re-start assigning from the first Cleaner task group.

[a2t.txt](https://github.com/JamesBremner/Agents2Tasks/files/13462867/a2t.txt)
[a2t_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/13462868/a2t_result.txt)

**Comment by JamesBremner** [comment]
> There is problem when the number of time slots for Cleaners is greater then the number of Cleaner task groups.

In your spec file there are 3 timeslots that ask for clearers

```
t 202312051000 Cleaner
t 202312121000 Cleaner
t 202312191000 Cleaner
```

There are also three Cleaner groups

```
g Cleaner mwalsh@gmail.com&2010-01-01
g Cleaner ismith@gmail.com&1961-07-02 rejkid@gmail.com&1961-03-24 asmith@gmail.com&1998-06-07
g Cleaner ablack@gmail.com&1998-06-07 iwhite@gmail.com&1961-07-02 awhite@gmail.com&1998-06-07 iblack@gmail.com&1961-07
```

Timeslots for clearer = cleaner groups.

**Comment by rejkid** [comment]
Look in the attached files. There are three Cleaner groups
g Cleaner ablack@gmail.com&1998-06-07 iwhite@gmail.com&1961-07-02 awhite@gmail.com&1998-06-07 iblack@gmail.com&1961-07-02
g Cleaner rejkid@gmail.com&1961-03-24 ismith@gmail.com&1961-07-02 asmith@gmail.com&1998-06-07
g Cleaner mwalsh@gmail.com&2010-01-01

... and 5 time slots for Cleaners tasks
t 202312051000 Cleaner
t 202312121000 Cleaner
t 202312191000 Cleaner
t 202312261000 Cleaner
t 202401021000 Cleaner

**Comment by JamesBremner** [comment]
You are right.  I was looking at the wrong file.  

The problem is that you post different files all with the same name, `a2t.txt`.  It gets very confusing.  Please use different names for different tiles.  Have you noticed how I handle this?  Each file is named for the issue concerned - so ex27.txt is the example input created for issue 27 and the result file is ex27r.txt.  Please use this or some equivalent naming convention.

**Comment by JamesBremner** [comment]
Here is a simple example to demonstrate the problem

```
a Carol 1 C cleaner
a Bob 1 B cleaner
a Alice 1 A cleaner
t 2023051100 cleaner
t 2023061100 cleaner
t 2023071100 cleaner
t 2023081100 cleaner
t 2023101100 cleaner
t 2023112110 cleaner
```

[ex35.txt](https://github.com/JamesBremner/Agents2Tasks/files/13464537/ex35.txt)

**Comment by JamesBremner** [comment]
**Cause**: Each timeslot starts with the agents in the order they were at the end of the previous timeslot.  This causes unexpected results dependent on what happened in the previous timeslot (  rate-independent hysteresis ).  So, in ex35, at the end of the 3rd timeslot agent Alice has the lowest workload so she is at the top of agent order.  At the start of timeslot 4 all agents have the same workload, so Alice is not moved from the top by the stable sort by workload and so is assigned to this timeslot too.

**Fix**: Restore input agent order at the start of each timeslot, preventing any hysteresis.

**Comment by rejkid** [comment]
Looks very promising. I have gone through every assignment manually making sure the output is as expected.

[a2t_result.#35.txt](https://github.com/JamesBremner/Agents2Tasks/files/13465998/a2t_result.35.txt)
