### ISSUE TITLE
Partial family assigned to time slot

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#36]
[a2t#36.txt](https://github.com/JamesBremner/Agents2Tasks/files/13468686/a2t.36.txt)
[a2t_result#36.txt](https://github.com/JamesBremner/Agents2Tasks/files/13468687/a2t_result.36.txt)
Hi James,
I am now randomly testing the assignments, using my GUI that generates input file and runs your task.
I came across this input file and the result file that:
1) In the first time slot "202310220830" contains partial family of dxuereb@gmail.com (only two members instead of all three members)

It is a bug isn't it?

**Comment by JamesBremner** [comment]
That is the main difference between a family and a group.  A family will be assigned to a timeslot together, if possible.  A group _must_ be be assigned to a timeslot as one, without being broken up.

**Comment by JamesBremner** [comment]
You are right.

**Comment by rejkid** [comment]
Can that be fixed for the same payment

**Comment by JamesBremner** [comment]
Can what be fixed?

**Comment by JamesBremner** [comment]
I think you may be confused by the differences between family and group membership.  This was discussed in November.  The discussion is recorded in the thread above.  Please read the thread.

Here is a table summarizing  the most significance differences between a family and a group.

| Family | Group |
|---|---|
Family membership specified in 'a' record | Group membership specified in 'g' record
Agent can belong to just one family | Agent can belong to several groups
Partial family can be assigned to task | Entire group assigned to task

**Comment by rejkid** [comment]
Maybe I don't understand something, but I can't see a reason why all three members of the family dxuereb@gmail.com can't be assigned together to the time slot "202310220830"?

**Comment by JamesBremner** [comment]
A specified task requires one agent or one group to be assigned to it.  

Families are, for preference, assigned to the same timeslot, each member of the family being assigned to one of the tasks in the timeslot that they are able to do.

So, if you want all the members of a family to be assigned to a timeslot, you need to specify tasks in that timeslots that all the family members are able to do - enough of them to occupy all the family members.

**Comment by JamesBremner** [comment]
> I can't see a reason why all three members of the family [dxuereb@gmail.com](mailto:dxuereb@gmail.com) can't be assigned together to the time slot "202310220830"?

What input are you referring to?  I thought maybe the one you posted to https://github.com/JamesBremner/Agents2Tasks/issues/40#issuecomment-2003186254 but there is no timeslot "202310220830" in that input.

**Comment by rejkid** [comment]
I was referring to this issue file a2t.36.txt

**Comment by JamesBremner** [comment]
Here is the timeslot spec

`t 202310220830 Acolyte Acolyte MAS MAS Reader1 Reader2 EMHC EMHC`

Here is the assignments for this timeslot

```
A 202310220830 ismith@gmail.com&1961-07-02 to Acolyte
A 202310220830 jblack@gmail.com&1961-03-24 to Acolyte
A 202310220830 dxuereb@gmail.com&1980-01-01 to MAS
A 202310220830 rejkid@gmail.com&1992-08-28 to MAS
A 202310220830 dxuereb@gmail.com&1979-01-01 to Reader1
A 202310220830 rejkid@gmail.com&1998-06-07 to Reader2
A 202310220830 jsmith@gmail.com&1961-03-24 to EMHC
```

**Comment by JamesBremner** [comment]
So, the reason that the family is not all assigned to this timeslot is due to the input order.  

The first task input is assigned to the first agent that is able to do it.  In this case `ismith@gmail.com&1961-07-02` who is NOT a member of the family.  By the time a member of the family is assigned to a task, the remaining unassigned tasks do not fit with the remaining members of the family.

I suggest that, instead of sprinkling the family members at random through the input, you should place them together early in the input.

**Comment by rejkid** [comment]
So if I sort them according to the family name before I pass them to the Agents2Tasks - that should fix the problem, shouldn't it?

**Comment by JamesBremner** [comment]
That is my reccomendation if your priority is to assign family members together.  The thing to keep in mind is that, all things being equal, the agents are assigned in the order they are input.  When an agent is assigned to a timeslot, THEN other members of that family are assigned preferentially.

**Comment by rejkid** [comment]
OK. Thank you for the hint. I will do that during the day. It's 3AM my time. I will let you know how I go. Should I close the issue for now?

**Comment by JamesBremner** [comment]
The issue should remain open until you complete testing it.

**Comment by rejkid** [comment]
[a2t_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/14663293/a2t_result.txt)

Agents2Tasks failed to assign dxuereb@gmail.com&01-01-1979 on 202402250830 - see my markups inside the file. You can see I have sorted agents by family and their count.

**Comment by rejkid** [comment]
So that can't be fixed?

**Comment by JamesBremner** [comment]
What do you mean by "that".  

Do you want to change the algorithm?

If you want to change the algorithm, you will need to describe exactly how you want the new algorithm to work.  I suggest you open a new issue.

FYI the current algorithm is documented here https://github.com/JamesBremner/Agents2Tasks/blob/main/README.md

**Comment by rejkid** [comment]
I suggest let's leave it the way it is for the time being. Should I close the issue?
