### ISSUE TITLE
Testing finished

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#37]
Hi James,
Thank you very much for the help you have given to me over the last couple of weeks.
If I ever make some profit from the application I have prepared, that includes your work, I will be sure to share the profit with you.

Kind Regards,
Janusz

Would that be a summary of the implementation of the algorithm:

The input consists of three sections in an input file:
                * Agent specification
                * Group Agent specification
                * Timeslot specification

Agents can perform the following tasks: Cleaner Acolyte MAS EMHC Reader2 Reader1 - multiple tasks can be assigned to an agent.

1) If the agent can do "Cleaner" task, he/she will belong to one group (A or B or C etc).
A group is a set of agents working together on a particular task; in this case the "Cleaner" task. Groups perform their duties on a weekly basis (as per time slot assignments). For example, group "A" does cleaning on one Saturday, then group B does the following Saturday. This continues with the groups until all groups have done their duties once and then the process of assigning starts from the beginning. Groups are never broken - they consist always of the same members.

2) If the agent can do any other task than "Cleaner", he/she will be part of the family that do those tasks preferably together (as a family).
They perform their duties based on the time slots. The assignment of agents to a time slot should follow the below rules(prioritized according to the list order):
                a) assigning Agent A to a task with the name T prevents them from being assigned to any other task for the same or next day
                b) assigning family members to the same time slot is preferred - if the family members are exhausted, then the other agents should be used
                c) attempt to evenly spread assignment amongst all agents

**Comment by JamesBremner** [comment]
There is nothing actually wrong in your description of how things work.  However, the way your description is written, it seems that the options are severely limited to the examples you mention.  In reality, the possibilities that can be specified are much broader.  For example, group tasks do not **have** to be weekly

It is much better, I think, to clearly separate the feature description and the example of how the feature might be used, so as to avoid the suggestion that a feature can only be used in some limited way.

Details:

> Agents can perform the following tasks: ....

Agents can perform any task that they are specified able to do.

> If the agent can do "Cleaner" task, he/she will belong to one group (A or B or C etc).

Groups can do whatever task the group is specified as being able to do, not just a 'Cleaner'.  There can be any number of group tasks, with each group able to do one of them.

Agents are members of a group if the group is specified as containing them.  Agent membership of a group has nothing to do with the tasks the agent can do.

Although this is not enforced, it is probably a very good idea to be clear which tasks require a single agent and which tasks require a group.  Do no specify single agents able to do group tasks nor groups able to do single agent tasks.

> Groups perform their duties on a weekly basis 

A Group performs their task whenever a timeslot is specified to contain the group task, no matter the frequency.  If you want the group to work on a weekly basis you have to specify the timeslots accordingly.

> Groups are never broken - they consist always of the same members.

Yes.  Note also that if any member of a group is clocked, then the entire group is blocked.

**Comment by JamesBremner** [comment]
Here is the complete feature definition https://github.com/JamesBremner/Agents2Tasks/wiki/Feature-Definition

**Comment by rejkid** [comment]
Thank you James for writing the "Feature-Definition" and a very comprehensive comments about my summary.

**Comment by JamesBremner** [comment]
Why is this assigned to me?

**Comment by JamesBremner** [comment]
No response, so closing this.
