### ISSUE TITLE
Group member specification

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#38]
I am still refactoring my code and i came across an unspecified error code 25 (the output message on the console says "25 Unspecified group member asmith@gmail.com&1998-06-07") - this is generated with the input file I attached.

I have noticed that in my previous input files records "a" contained agents assigned to Cleaner task have "none" specified as a task - so I removed all "none" records from input file (that why I am getting error 25 now). I can't remember if that was something we have agreed on or not.
Do we need in agent specification section records that say "none" for agents that are assigned to Cleaner tasks? :
"a asmith@gmail.com&1998-06-07 1 asmith@gmail.com none"
... or I can remove them. Its OK if we need to keep them, I am just asking. Maybe I forgot about something we have agreed on.
An example file that contains those "none" records "a" is the file dat/ex27jr.txt.

[a2t_radom_test.txt](https://github.com/JamesBremner/Agents2Tasks/files/13533946/a2t_radom_test.txt)

**Comment by JamesBremner** [comment]
Well, that was the design intent.  However, I added a unit test to confirm and it turns out that agents with no tasks are not allowed.  I will fix.

**Comment by JamesBremner** [comment]
Updated status code docs

**Comment by JamesBremner** [comment]
Have you read the error message?

`25 Unspecified group member asmith@gmail.com&1998-06-07`

This gives you all the information you need to solve the problem.  You have specified that group member without specifying the agent with that name.

Please remember to actually read the error message.

**Comment by JamesBremner** [comment]
No response, so closing this.

**Comment by rejkid** [comment]
OK
