### ISSUE TITLE
Duplicate group member

### ISSUE THREAD

**Issue by ghost** [JamesBremner/Agents2Tasks#39]
Hi James,
How are you doing?
Justa quick question. Long story short - I am still testing the software with the client. Just a recent thing that came up with the testing is an error "Duplicate group member". It gets generated if one agent is a member of two groups - is that a bug or a requirement change? - I can't remember. Could you please help me with that?

**Comment by ghost** [comment]
Sorry. My question is not clear. What I am asking is : Is it allowed for one agent to be member of two groups?

**Comment by ghost** [comment]
[a2t.txt](https://github.com/JamesBremner/Agents2Tasks/files/14581006/a2t.txt)

**Comment by JamesBremner** [comment]
Have you looked at #27?

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/65b65645-acbc-469e-a8e3-0177071247fe)

**Comment by ghost** [comment]
I have accidently removed me as assigned. Can we change that please so the agent can have membership of multiple groups?

**Comment by ghost** [comment]
I don't currently have permission to view any of the old issues?

**Comment by JamesBremner** [comment]
I guess the problem is that you now have two github accounts.  Login as rejkid rather than rejkid-tester.

You should only have one account.

**Comment by rejkid** [comment]
OK. I have signed out from rejkid-tester and I have access to old issues now.
So the question is: can we make a change please so the agent can have membership of multiple groups?

**Comment by JamesBremner** [comment]
You have assigned yourself to this issue.

OK, do you know the process?

- Fork the repo
- Make the change
- Test the change.
- Commit the change
- Submit a pull request

**Comment by rejkid** [comment]
I have assigned yourself to the issue. Could you fix it please. I don't have enough knowledge to do that.

**Comment by JamesBremner** [comment]
What financial support are you offering for this work?

**Comment by rejkid** [comment]
How much is it worth in your opinion?

**Comment by JamesBremner** [comment]
It is worth nothing at all to me.  You are the person who is asking for this work to be done.

**Comment by JamesBremner** [comment]
That's OK, I can wait until you are able to offer financial support.

**Comment by rejkid** [comment]
I am prepared to pay now. I have never bought anything like that over internet. Just tell me the price. I want to demonstrate that it works to the client?

**Comment by JamesBremner** [comment]
There are almost 1000 lines of code in the repo, all debugged and extensively tested.  The work took was done over a full month in November of last year. 

I suggest extending support for this code for one month ( up to April 13th ).  Charge would be USD 250.

**Comment by rejkid** [comment]
Is it possible to pay you via PayPal? Please provide me the details and I'll organize it.

**Comment by JamesBremner** [comment]
Paypal works well for me.  

If you send me an email I can reply with a Paypal invoice.  My email is shown in my github profile https://github.com/JamesBremner ( I do not have your email.)

**Comment by rejkid** [comment]
How do you want to tackle the issue.
I can provide in the input text for you at the end of each group line the name of the group that would be unique within the group  task - if that helps.

**Comment by JamesBremner** [comment]
The group name is automatically generated from the first member of the group.  If you do not want to get duplicate group names, then the first member of every group must be a member of  one group only.

Like this

```
a mwalsh 1 mwalsh MAS
a example 1 example Acolyte
g Cleaner mwalsh
g Cleaner example mwalsh
t 202312051000 Cleaner
t 202312121000 Cleaner
t 202312191000 Cleaner
t 202312261000 Cleaner
t 202401021000 Cleaner
A 202312051000 mwalsh_group to Cleaner
A 202312051000 mwalsh in mwalsh_group to Cleaner
A 202312121000 example_group to Cleaner
A 202312121000 example in example_group to Cleaner
A 202312121000 mwalsh in example_group to Cleaner
A 202312191000 mwalsh_group to Cleaner
A 202312191000 mwalsh in mwalsh_group to Cleaner
A 202312261000 example_group to Cleaner
A 202312261000 example in example_group to Cleaner
A 202312261000 mwalsh in example_group to Cleaner
A 202401021000 mwalsh_group to Cleaner
A 202401021000 mwalsh in mwalsh_group to Cleaner
```

Let me know if you would prefer a user supplied group name, which the code could check for uniqueness.

**Comment by JamesBremner** [comment]
Is there some reason you are keeping this issue open?
