### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#4]
Agents2Tasks crashes after entering couple of different tasks agents and time slots - do you maintain some log files - very hard to reproduce.

Would it be possible to provide as inputs two xlsm spreadsheets ( or comma separated files) as:
1) Sheet: 
e.g 
Agent1, Taks1(cost1) Task2(cost1) Task3(cost1)
Agent2, Taks1(cost1) Task2(cost1)
Agent3, Task2(cost1) Task3(cost1)
...

2) Sheet:
Timeslot: 13-11-2023 Task1 Task1 Task2 Task2 Task3
		  20-11-2023 Task1 Task2 Task2 Task3
		  27-11-2023 Task2 Task2 Task3
		  
and have agents2tasks generate the assignments?

**Comment by JamesBremner** [comment]
Please look at the documents in the readme and the wiki. They describe how to input a problem spec from file and how to format the input file.
