### ISSUE TITLE
User supplied group name

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#40]
The group name is automatically generated from the first member of the group. If you do not want to get duplicate group name errors, then the first member of every group must be a member of one group only.

```
C:\Users\James\code\Agents2Tasks\bin>Agents2Tasks.exe ../dat/ex39-2.txt ex39r.txt
Unit tests passed

12      Duplicate group name mwalsh_group
status 12
```

Suggested in #39, the user could supply the group names.

| Field | Value | Description
|---|---|---|
0 | 'g' | identifies a line specifying a group
**1 | string, no spaces | group name**
2 | string, no spaces | group task name
3 | space delimited list of strings | agents that belong to the group

Let me know here if you want to do this.

**Comment by rejkid** [comment]
Yep. Could you check if the initial input test is OK.
[a2t.txt](https://github.com/JamesBremner/Agents2Tasks/files/14617521/a2t.txt)

**Comment by JamesBremner** [comment]
> g Cleaner A rejkid@gmail.com&07-06-1998  rose@ourladyoftheangels.org.au&24-03-1961 

I think you mean to specify a group named "A" that can be assigned to a "Cleaner" task.  You have reversed the order of the name and task fields.

**Comment by rejkid** [comment]
Sorry. 
Stand corrected.
[a2t_40.txt](https://github.com/JamesBremner/Agents2Tasks/files/14617925/a2t_40.txt)

**Comment by JamesBremner** [comment]
a2t_40 output

```
a rejkid@gmail.com&07-06-1998 1 rejkid@gmail.com Cleaner
a rose@ourladyoftheangels.org.au&24-03-1961 1 rose@ourladyoftheangels.org.au Cleaner Welcomer
a pmurphy@gmail.com&24-03-1961 1 pmurphy@gmail.com Welcomer Collector
a rejkid@gmail.com&28-08-1992 1 rejkid@gmail.com Cleaner Collector
a rejkid@gmail.com&02-07-1961 1 rejkid@gmail.com Cleaner
g A Cleaner rejkid@gmail.com&07-06-1998 rose@ourladyoftheangels.org.au&24-03-1961
g B Cleaner rejkid@gmail.com&28-08-1992 rejkid@gmail.com&02-07-1961
g Rose Welcomer rose@ourladyoftheangels.org.au&24-03-1961 pmurphy@gmail.com&24-03-1961
g Peter Collector pmurphy@gmail.com&24-03-1961 rejkid@gmail.com&28-08-1992
t 202402030600 Cleaner
t 202402040830 Welcomer
t 202402041000 Collector
t 202402110830 Welcomer
t 202402111000 Collector
A 202402030600 A_group to Cleaner
A 202402030600 rejkid@gmail.com&07-06-1998 in A to Cleaner
A 202402030600 rose@ourladyoftheangels.org.au&24-03-1961 in A to Cleaner
A 202402040830 pmurphy@gmail.com&24-03-1961 to Welcomer
A 202402041000 rejkid@gmail.com&28-08-1992 to Collector
A 202402110830 Rose_group to Welcomer
A 202402110830 rose@ourladyoftheangels.org.au&24-03-1961 in Rose to Welcomer
A 202402110830 pmurphy@gmail.com&24-03-1961 in Rose to Welcomer
A 202402111000 rejkid@gmail.com&28-08-1992 to Collector
```

**Comment by rejkid** [comment]
Hi James, I am getting an exception as attached.:
![Screenshot 2024-03-16 060752](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/aa533478-73b1-42eb-a0d8-83cbeae2f17e)

**Comment by JamesBremner** [comment]
Does this happen when you use a2t_40.txt?

**Comment by rejkid** [comment]
Yep

**Comment by JamesBremner** [comment]
I cannot reproduce that.  Are you sure that you are using the latest version?  Please post your build log

**Comment by JamesBremner** [comment]
I get:

```
C:\Users\James\code\Agents2Tasks\bin>Agents2Tasks.exe ../dat/a2t_40.txt ../dat/r.txt
Unit tests passed
```

**Comment by rejkid** [comment]
![Screenshot 2024-03-16 062323](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/2ff8d052-af35-49b6-9498-bb0cbfcee08b)

**Comment by rejkid** [comment]
Do I need to update raven-set ?

**Comment by JamesBremner** [comment]
Depends.  Do you have the latest version?

**Comment by rejkid** [comment]
![Screenshot 2024-03-16 062912](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/851c1e8a-e490-48ac-bed8-e1e5fe93de47)

**Comment by JamesBremner** [comment]
Please check that your have the latest version of a2t.  Your history should look like this:

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/481cadbe-26e6-484d-954b-de3d4b6162d7)

**Comment by JamesBremner** [comment]
You need to update raven-set

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/bc6ab91e-f8de-43d2-ba2f-2a9193e05a53)

**Comment by rejkid** [comment]
![Screenshot 2024-03-16 063301](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/2edad746-59c7-4cdb-a7f2-73c26a94db0a)

**Comment by rejkid** [comment]
My rave-set now looks like:
![Screenshot 2024-03-16 063926](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/15297764-b691-4279-9547-9ab8c617ee13)

**Comment by JamesBremner** [comment]
If you are getting unit test failures with a build of the latest software then there must be something wrong with your build.  Your build log looks OK though.

Try running my build
[Agents2Tasks.zip](https://github.com/JamesBremner/Agents2Tasks/files/14620116/Agents2Tasks.zip)

**Comment by JamesBremner** [comment]
This is wrong!!!

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/11e5694d-a657-4b58-956a-642a1f9163da)

Do a rebuild with the latest software.

**Comment by rejkid** [comment]
That was just an old message - sorry I shouldn't include it on the attached file - I have the latest software downloaded. 
![Screenshot 2024-03-16 065105](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/a1c23326-2f02-4104-bb49-6d0f5f18ebf2)

**Comment by JamesBremner** [comment]
Have you run my build?

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/8517ade5-7e52-4bf8-b783-09114d54e642)

This indicates that the unit test method has returned with false.  If you look at the code in unitest.cpp you will see that there is no return false statement.  There is something badly wrong with your build.

**Comment by rejkid** [comment]
I am struggling now with Norton removing your file when I try to run it.
The size of your Agents2Tasks.exe is 12,563 KB main is 4.66 MB.

**Comment by JamesBremner** [comment]
You are building the debug version - so it is much bigger.

Your anti-virus is way too aggressive.  You need to calm it down so you can develop software.  Whitelist agents2tasks.exe

**Comment by rejkid** [comment]
I am trying but can't find the way to

**Comment by rejkid** [comment]
Your build is 12.2 MB, main is only 4.66 MB - so it looks like you have a debug version - isn't it?

**Comment by rejkid** [comment]
I am restarting my machine

**Comment by JamesBremner** [comment]
That is the same error as you reported initially.  If you look at the code, you will see that there is now way to get there.  Explanation here https://github.com/JamesBremner/Agents2Tasks/issues/40#issuecomment-2000376532.  

Suggestion.  Build the debug version and run it under the debugger to see how you are getting that error.

**Comment by JamesBremner** [comment]
Found the problem

**Comment by JamesBremner** [comment]
Pull, rebuild and the unit test should run successfully

**Comment by JamesBremner** [comment]
Sorry about that!  I made a last minute change to how the output file displays the group names, which broke the unit tests, but I must have run the unit tests on the unchanged code.

**Comment by rejkid** [comment]
That's OK. Your test passes now my code is broken - so must look into.

**Comment by rejkid** [comment]
Hi James. I need to filter out the records like "A 202402030600 A_group to Cleaner" as they don't contain any useful data for me. Can we agree that those records will always contain underscore and no other records will so I can easily filter them out? So no change would be required.

**Comment by JamesBremner** [comment]
Yes.  

Except that you must never specify an agent or a test with an underscore.

You will be safer to ignore records that contain "_group"

**Comment by rejkid** [comment]
You are right I will filter out all records with _group - we agree on that.

**Comment by rejkid** [comment]
Hi James,
Just a question:
How come there are some records with "in <_GroupName_>" to indicate the group they belong to and some are without

**Comment by JamesBremner** [comment]
That means that agents have been assigned to tasks as individuals, not as group members.

**Comment by rejkid** [comment]
They do tasks in groups not as individuals. So there are two Collectors in group Peter - they should be assigned together just like Cleaners.

**Comment by JamesBremner** [comment]
Agents are assigned as individuals whether or not they belong to a group.  Belonging a group does not prevent them from being assigned individually.

**Comment by rejkid** [comment]
Sorry. We have some misunderstanding. 
1) So in the test file provided:

the two below agents:
a)
rose@ourladyoftheangels.org.au&24-03-1961 
rejkid@gmail.com&07-06-1998 
appear in the "Cleaner" group "A" (together) and not as individuals.  (That is the way my client wants to treat the group)

b)
and those two agents:
pmurphy@gmail.com&24-03-1961
rose@ourladyoftheangels.org.au&24-03-1961
should appear in the "Welcomer" group "Rose" (together), not individually

c)
and those two agents:
rejkid@gmail.com&28-08-1992
pmurphy@gmail.com&24-03-1961
should appear in the "Collector" group "Peter"

* When the group is assigned to a date all agents belonging to that group should be assigned to that date (they do the task together)

* There are agents that don't belong to any group  - like Acolyte/Reader1/Reader2 - those are individuals and should be assigned individually as we described this in "Agent Assignment."

2) Why there is no "Peter_group to Collector" group row

**Comment by JamesBremner** [comment]
My best guess is that you want to specify an agent that only gets assigned to task in a group, never individually.

To prevent an agent being assigned individually to a task do NOT specify any individual tasks for that agent.

For example, if you want rose never to be assigned as an individual, use a specification like this

`a rose 1 rose NoIndividualTasks`

which will give you

```
a rejkid@gmail.com&07-06-1998 1 rejkid@gmail.com Cleaner
a rose 1 rose NoIndividualTasks
a pmurphy@gmail.com&24-03-1961 1 pmurphy@gmail.com Welcomer Collector
a rejkid@gmail.com&28-08-1992 1 rejkid@gmail.com Cleaner Collector
a rejkid@gmail.com&02-07-1961 1 rejkid@gmail.com Cleaner
g A Cleaner rejkid@gmail.com&07-06-1998 rose
g B Cleaner rejkid@gmail.com&28-08-1992 rejkid@gmail.com&02-07-1961
g Rose Welcomer rose pmurphy@gmail.com&24-03-1961
g Peter Collector pmurphy@gmail.com&24-03-1961 rejkid@gmail.com&28-08-1992
t 202402030600 Cleaner
t 202402040830 Welcomer
t 202402041000 Collector
t 202402110830 Welcomer
t 202402111000 Collector
A 202402030600 A_group to Cleaner
A 202402030600 rejkid@gmail.com&07-06-1998 in A to Cleaner
A 202402030600 rose in A to Cleaner
A 202402040830 pmurphy@gmail.com&24-03-1961 to Welcomer
A 202402041000 rejkid@gmail.com&28-08-1992 to Collector
A 202402110830 Rose_group to Welcomer
A 202402110830 rose in Rose to Welcomer
A 202402110830 pmurphy@gmail.com&24-03-1961 in Rose to Welcomer
A 202402111000 rejkid@gmail.com&28-08-1992 to Collector
```

**Comment by rejkid** [comment]
Let's take it bit by bit. What I am after is this. 
1) I want to change only a "Group assignment" specification like following:
Group Cleaner A is defined as two agents:
	rose@ourladyoftheangels.org.au&24-03-1961 
	rejkid@gmail.com&07-06-1998 

Group Cleaner B is defined as two agents:
	rejkid@gmail.com&28-08-1992
	rejkid@gmail.com&02-07-1961 
	
All I want is that whenever I specify time slot: "t 202402030600 Cleaner" I would like A2T to assign the whole Cleaner group to that date: So either the whole "Group Cleaner A" or whole "Group Cleaner B" should be assigned to that date.
The output should look like this:

A 202402030600 rejkid@gmail.com&07-06-1998 in A to Cleaner
A 202402030600 rose@ourladyoftheangels.org.au&24-03-1961 in A to Cleaner

or

A 202402030600 rejkid@gmail.com&28-08-1992 in B to Cleaner
A 202402030600 rejkid@gmail.com&02-07-1961 in B to Cleaner

Similarly for other groups (Welcomer/Collector)

2) Assignments of individual agents (Acolyte/Reader1/Reader2 etc) should work exactly how they worked previously - as described in "Agent Assignment" - only Group assignment should be changed as above.

**Comment by JamesBremner** [comment]
> I want to change only a "Group assignment" specification like following:
> Group Cleaner A is defined as two agents:
> [rose@ourladyoftheangels.org.au](mailto:rose@ourladyoftheangels.org.au)&24-03-1961
> [rejkid@gmail.com](mailto:rejkid@gmail.com)&07-06-1998
> Group Cleaner B is defined as two agents:
> [rejkid@gmail.com](mailto:rejkid@gmail.com)&28-08-1992
> [rejkid@gmail.com](mailto:rejkid@gmail.com)&02-07-1961

You have that now:

```
g A Cleaner rejkid@gmail.com&07-06-1998  rose@ourladyoftheangels.org.au&24-03-1961 
g B Cleaner rejkid@gmail.com&28-08-1992  rejkid@gmail.com&02-07-1961 
```

So, no change to group specification.

-----------------------

> 
> The output should look like this:
> 
> A 202402030600 [rejkid@gmail.com](mailto:rejkid@gmail.com)&07-06-1998 in A to Cleaner
> A 202402030600 [rose@ourladyoftheangels.org.au](mailto:rose@ourladyoftheangels.org.au)&24-03-1961 in A to Cleaner

The output does look like that!

**Comment by rejkid** [comment]
But it should also look the same for other groups (for example for the group "g Rose Welcomer rose@ourladyoftheangels.org.au&24-03-1961 pmurphy@gmail.com&24-03-1961")
 
Group Rose Welcomer  is defined as two agents:
	rose@ourladyoftheangels.org.au&24-03-1961
	pmurphy@gmail.com&24-03-1961 

For the slot : "A 202402040830" I would like A2T assigns the whole group to that date.
So the output should look like this:

A 202402040830 rose@ourladyoftheangels.org.au&24-03-1961 to Welcomer
A 202402040830 pmurphy@gmail.com&24-03-1961 to Welcomer

and so on....

**Comment by JamesBremner** [comment]
> For the slot : "A 202402040830" I would like A2T assigns the whole group to that date.
> So the output should look like this:
> 
> A 202402040830 [rose@ourladyoftheangels.org.au](mailto:rose@ourladyoftheangels.org.au)&24-03-1961 to Welcomer
> A 202402040830 [pmurphy@gmail.com](mailto:pmurphy@gmail.com)&24-03-1961 to Welcomer

With your specs you get

`A 202402040830 pmurphy@gmail.com&24-03-1961 to Welcomer`

As I explained above ( https://github.com/JamesBremner/Agents2Tasks/issues/40#issuecomment-2001987240 ) if you do not want an agent assigned individually, you should stop specifying that agent as able to do tasks that can be done by groups.

So, like this:

`a pmurphy@gmail.com&24-03-1961 1 pmurphy@gmail.com NoIndividualTasks`

**Comment by JamesBremner** [comment]
Here is a complete specification that ensures all agents are assigned in groups

```
a rejkid-1 1 rejkid NoIndividualTasks
a rose 1 rose NoIndividualTasks
a pmurphy 1 pmurphy NoIndividualTasks
a rejkid-2 1 rejkid NoIndividualTasks
a rejkid-3 1 rejkid NoIndividualTasks
g A Cleaner rejkid-1 rose
g B Cleaner rejkid-2 rejkid-3
g Rose Welcomer rose pmurphy
g Peter Collector pmurphy rejkid-3
t 202402030600 Cleaner
t 202402040830 Welcomer
t 202402041000 Collector
t 202402110830 Welcomer
t 202402111000 Collector
A 202402030600 A_group to Cleaner
A 202402030600 rejkid-1 in A to Cleaner
A 202402030600 rose in A to Cleaner
A 202402041000 Peter_group to Collector
A 202402041000 pmurphy in Peter to Collector
A 202402041000 rejkid-3 in Peter to Collector
A 202402110830 Rose_group to Welcomer
A 202402110830 rose in Rose to Welcomer
A 202402110830 pmurphy in Rose to Welcomer
```

**Comment by rejkid** [comment]
Hi James . Going back to test a2t_40 output? Could you confirm the question I have put in the output file. I think I found a reason why some Cleaner/Welcomer are missing for certain dates from output.

a rejkid@gmail.com&07-06-1998 1 rejkid@gmail.com Cleaner
a rose@ourladyoftheangels.org.au&24-03-1961 1 rose@ourladyoftheangels.org.au Cleaner Welcomer
a pmurphy@gmail.com&24-03-1961 1 pmurphy@gmail.com Welcomer Collector
a rejkid@gmail.com&28-08-1992 1 rejkid@gmail.com Cleaner Collector
a rejkid@gmail.com&02-07-1961 1 rejkid@gmail.com Cleaner
g A Cleaner rejkid@gmail.com&07-06-1998 rose@ourladyoftheangels.org.au&24-03-1961
g B Cleaner rejkid@gmail.com&28-08-1992 rejkid@gmail.com&02-07-1961
g Rose Welcomer rose@ourladyoftheangels.org.au&24-03-1961 pmurphy@gmail.com&24-03-1961
g Peter Collector pmurphy@gmail.com&24-03-1961 rejkid@gmail.com&28-08-1992
t 202402030600 Cleaner
t 202402040830 Welcomer
t 202402041000 Collector
t 202402110830 Welcomer
t 202402111000 Collector

A 202402030600 A_group to Cleaner
A 202402030600 rejkid@gmail.com&07-06-1998 in A to Cleaner
A 202402030600 rose@ourladyoftheangels.org.au&24-03-1961 in A to Cleaner

A 202402040830 pmurphy@gmail.com&24-03-1961 to Welcomer
? Is rose missing because she was Cleaner on 202402030600

A 202402041000 rejkid@gmail.com&28-08-1992 to Collector
? Is pmurphy@gmail.com&24-03-1961 because he was Welcomer on 202402040830

A 202402110830 Rose_group to Welcomer
A 202402110830 rose@ourladyoftheangels.org.au&24-03-1961 in Rose to Welcomer
A 202402110830 pmurphy@gmail.com&24-03-1961 in Rose to Welcomer

A 202402111000 rejkid@gmail.com&28-08-1992 to Collector
? Is pmurphy@gmail.com&24-03-1961 missing because he was Welcomer on 202402110830

**Comment by JamesBremner** [comment]
The answer to all your questions is yes.  The algorithm tries to even out the workload between available agents by picking the agents that have the lowest previous workload.

**Comment by rejkid** [comment]
Then it seems to be working OK. I was wrong. Sorry about that.

I am still testing. I found scenario where there seems to be a small problem.
Is there any reason why kbozym@gmail.com&24-03-1961 is not assigned as a Collector to a date 202402040830 in the below case? I understand the rejkid@gmail.com&24-03-1961 is not assigned because it was assigned as Cleaner on 202402030600.

a rejkid@gmail.com&24-03-1961 1 rejkid@gmail.com Cleaner Collector
a dbozym@gmail.com&24-03-1961 1 dbozym@gmail.com Collector
a kbozym@gmail.com&24-03-1961 1 kbozym@gmail.com Collector
g A Cleaner rejkid@gmail.com&24-03-1961
g Kazik Collector rejkid@gmail.com&24-03-1961 dbozym@gmail.com&24-03-1961 kbozym@gmail.com&24-03-1961
t 202402030600 Cleaner
t 202402040830 Acolyte Collector
A 202402030600 A_group to Cleaner
A 202402030600 rejkid@gmail.com&24-03-1961 in A to Cleaner
A 202402040830 dbozym@gmail.com&24-03-1961 to Collector

**Comment by JamesBremner** [comment]
Did you run it with the explainer enabled? #41

**Comment by JamesBremner** [comment]
> Is there any reason why [kbozym@gmail.com](mailto:kbozym@gmail.com)&24-03-1961 is not assigned as a Collecto

dbozym was assigned instead because that agent was input first.  If all else is equal then the first input agent is assigned.

**Comment by JamesBremner** [comment]
Note that this was discussed in #35

**Comment by rejkid** [comment]
Do I need to pull & rebuild the Agents2Tasks to have explainer working?

**Comment by JamesBremner** [comment]
Yes, of course!

**Comment by rejkid** [comment]
Now it does not produce any output with the input:

a kbozym@gmail.com&24-03-1961 1 kbozym@gmail.com Collector
a rejkid@gmail.com&24-03-1961 1 rejkid@gmail.com Collector
a dbozym@gmail.com&24-03-1961 1 dbozym@gmail.com Collector
g Kazik Collector kbozym@gmail.com&24-03-1961 rejkid@gmail.com&24-03-1961 dbozym@gmail.com&24-03-1961
t 202402030600 Cleaner
t 202402040830 Acolyte Collector

Can we revert Agents2Tasks to label "Fix unit tests #40" - it was working fine

**Comment by JamesBremner** [comment]
Cause: mishandles case where no available agents for task.  ( There is no agent able to do the Cleaner tesk. )

**Comment by JamesBremner** [comment]
Fixed

**Comment by rejkid** [comment]
What is "NoIndividualTasks" flag - If I don't use it at all should the build work as per "Fix unit tests #40"?
Because I want functionality exactly as per "Fix unit tests #40" - for as long as flag "NoIndividualTasks" not being used gives me that it's fine.

**Comment by JamesBremner** [comment]
It is not a flag.  It is an unspecified task name, used to prevent individual assignments.  I explained this here https://github.com/JamesBremner/Agents2Tasks/issues/40#issuecomment-2001987240

This was necessary at the time because the input parser did not handle agents with no tasks.  That is now fixed so use of this is optional.  I think it makes it clearer what you are doing - not just forgetting to specify tasks.

**Comment by JamesBremner** [comment]
This is a duplicate of #36

Please do not add a new issue on to the end of some random other issue.  Anyway this is NOT a new issue.  Please check on closed issues before reporting something - that is what they are the for.

**Comment by JamesBremner** [comment]
Hello?

Did you read the discussion in #36 about the difference between an agent's group and family memberships?  If that is still unclear then please re-open #36 and was can discuss it in more detail.

**This** issue is about user supplied group names, as opposed to automatic group naming.  It seems that this feature is now working and so I think this issue is ready to be closed.
