### ISSUE TITLE
Change balance between family assignment and work sharing

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#42]
We have thoroughly tested my implementation of your algorithm, checking that the family feature works as you designed it.

However, you seem to be surprised when entire families are not assigned to a timeslot.  Frequently families are not assigned together because some of their members have been assigned to tasks in previous timeslots and you required  that the workload should be distributed between agents as evenly as possible.

I asked if you wanted to change the algorithm in some way so that entire families were assigned more frequently.  ( The is what I guessed you meant when you wrote: "Can that be fixed"  Please try to be more explicit in future! )

You did not clarify what exactly you wanted, or suggest any changes to the algorithm.  So I thought it might be OK if I gave it a go!

I do not think you want to drop the work sharing feature, just to get more entire families assigned.  That would result in a family being assigned over and over again, while individual agents would get no work.  

A balancing act is needed, I think.  Changing the algorithm so that entire families are assigned by preference, so long as the agent's work loads do not become too unfair.

The way to do this, I suggest, is that each timeslot assignment be given a score.  Then a new assignment algorithm is implemented that prioritizes assigning entire families over any other consideration.  The new algorithm and the current algorithm are BOTH run for each timeslot and the assignment with the best score is used.

Assignment scoring will be fairly arbitrary and you will likely want to experiment with different parameters to get the kind of result you are comfortable with.  But to make things concrete I will suggest an initial scoring system like this

Each assigned agent that shares a family with another assigned agent scores      + 2
Each previous assignment of an agent assigned to this slot scores                        - 1

Let's see how that would work with this input

```
a aA 1 fA tA
a aC 1 fB tA
a aB 1 fA tA
t 202402010600 tA tA
t 202402080600 tA tA
t 2024020150600 tA tA
```

Each timeslot has two possible assignments

- the two members of family fA
- agent aC and one member of family fA

For the first timeslot, the assignment scores are

for the family         4 - 0 = 4
for the individual   0 - 0 = 0

So the family is assigned

For the second slot, the family members have previous assignments so the scores would be

for the family         4 - 2 = 2
for the individual   0 - 1 = 1

So the family is assigned, even though the family members have a workload of 2 and aC has no work.

The third slot scores are

for the family         4 - 4 = 0
for the individual   0 - 1 = 1

So this time the family is broken up because the work load have become too uneven.

Note that you can make the entire family assignments more or less proof against unfair work loads by simple adjustments to the scoring parameters.

Let me know if you have any interest in this suggestion.

**Comment by rejkid** [comment]
Hi James. Thank you for analyzing my concern in such a deep way. I think I want to keep things very simple. It's working alright for the time being (I want the workload to be distributed between agents as evenly as possible), but if the customer comes back to me saying they want to have more control over the assignment and they are ready to pay for this then I would say we consider your suggestion. How does that sound?

BTW
You probably meant:

- agent aC and one member of family **fB**
