### ISSUE TITLE
Group name specification missing in feature definition

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#43]
Group name doc not updated in feature definition ( It is OK in file format )

**Comment by JamesBremner** [comment]
Have you tested this?

This seems to be a duplicate of #39, in particular https://github.com/JamesBremner/Agents2Tasks/commit/5891614d6a75ea9f6eb924ac09122a49cb3121fc

5 days ago you closed #39.  Did you test it before you closed it?

**Comment by JamesBremner** [comment]
There was an error in the test file for #39.

Fixed now.

```
a mwalsh 1 mwalsh MAS
a example 1 example Acolyte
g A Cleaner mwalsh
g B Cleaner example mwalsh
t 202312051000 Cleaner
t 202312121000 Cleaner
t 202312191000 Cleaner
t 202312261000 Cleaner
t 202401021000 Cleaner
A 202312051000 A_group to Cleaner
A 202312051000 mwalsh in A to Cleaner
A 202312121000 B_group to Cleaner
A 202312121000 example in B to Cleaner
A 202312121000 mwalsh in B to Cleaner
A 202312191000 A_group to Cleaner
A 202312191000 mwalsh in A to Cleaner
A 202312261000 B_group to Cleaner
A 202312261000 example in B to Cleaner
A 202312261000 mwalsh in B to Cleaner
A 202401021000 A_group to Cleaner
A 202401021000 mwalsh in A to Cleaner
```

**Comment by JamesBremner** [comment]
Hello?

**Comment by rejkid** [comment]
Yep. Everything seems to be OK. I have some issues with my application. Would you mind updating documentation?

**Comment by rejkid** [comment]
User supplied group name #40 - the new format for group names

**Comment by JamesBremner** [comment]
Fixed
