### ISSUE TITLE
Specific feature of group tasks

### ISSUE THREAD

**Issue by ghost** [JamesBremner/Agents2Tasks#45]
Hi James,
Just a quick question. Is it right that group tasks are assigned sequentially after which they are re-used - meaning that if there are group tasks A B C and D they are assigned in time as A B C D and then again A B C D and so on?

**Comment by JamesBremner** [comment]
There is no such thing as a group task.  

Tasks are not re-used.  A particular task is assigned an agent once and once only.

As written, your question is meaningless.  My best guess is you are confused between tasks and agents.

When a group agent is assigned to a timeslot the individual agents are assigned to individual tasks in the order the agents were specified as belonging to the group.  Whenever the group is assigned to a timeslot, the same order is always used.

**Comment by rejkid** [comment]
Well. The documentation clearly defines group task, so we either remove or change that section in wiki doc.

**Comment by JamesBremner** [comment]
The "group task" mentioned in the wiki is the task type that the group can be assigned to.  There is no such thing as a group task.  I will clarify the wiki.

**Comment by JamesBremner** [comment]
I have removed "group tasks" from the wiki since they do not exist.

**Comment by rejkid** [comment]
Should we also rename Group as a Group Agent?

**Comment by JamesBremner** [comment]
If you want.

Can we close this issue?
