### ISSUE TITLE
Distribute work over multiple timeslots between extra agents

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Agents2Tasks#5]
Example

```
a John 1 accountant teacher 
a Janusz 1 teacher cleaner 
a Renia 1 accountant cleaner 
a Andrew 1 accountant teacher 
a James 1 cleaner teacher 
a Steven 1 accountant teacher 
t 28/OCT/2023/8:30 teacher teacher cleaner 
t 29/OCT/2023/10:00 teacher teacher cleaner 
t 2/NOV/2023/8:30 teacher teacher cleaner 
t 3/NOV/2023/10:00 teacher teacher cleaner 
t 4/NOV/2023/8:30 teacher teacher cleaner 
t 5/NOV/2023/10:00 teacher teacher cleaner 
F 28/OCT/2023/8:30 John to teacher
F 28/OCT/2023/8:30 Janusz to teacher
F 28/OCT/2023/8:30 James to cleaner
F 29/OCT/2023/10:00 John to teacher
F 29/OCT/2023/10:00 Janusz to teacher
F 29/OCT/2023/10:00 James to cleaner
F 2/NOV/2023/8:30 John to teacher
F 2/NOV/2023/8:30 Janusz to teacher
F 2/NOV/2023/8:30 James to cleaner
F 3/NOV/2023/10:00 John to teacher
F 3/NOV/2023/10:00 Janusz to teacher
...
```

@rejkid write in another issue

> The issue that I see is that the output is missing Steven and Andrew agens who can be an accountant or teacher.

**Comment by JamesBremner** [comment]
Your input has 6 agents.  The timeslots all have just three tasks.  Once all tasks have been assigned an agent, the problem is solved.

What did you expect to happen to the extra agents?

**Comment by rejkid** [comment]
I was hoping that the algorithm will spread the tasks amongst all the agents. For example after using John and Janusz  as teachers for the time slot  28/OCT/2023 algorithm would realise that there are other agents that could have also been  used, so for the next time slot  29/OCT/2023 would use them  (agent Andrew and Steven) - as they have not been used before. So at the end of the algorithm every agent is used at least once.

**Comment by JamesBremner** [comment]
The A2T algorithm does this.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/3b09f323-d474-4ca3-a603-9e06fc837efa)

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/5d344342-7eb2-47cb-add0-97de3335daeb)

**Comment by JamesBremner** [comment]
A 28/OCT/2023/8:30 John to teacher
A 28/OCT/2023/8:30 Janusz to teacher
A 28/OCT/2023/8:30 Renia to cleaner
A 29/OCT/2023/10:00 Andrew to teacher
A 29/OCT/2023/10:00 James to teacher
A 29/OCT/2023/10:00 Janusz to cleaner
A 2/NOV/2023/8:30 Steven to teacher
A 2/NOV/2023/8:30 Andrew to teacher
A 2/NOV/2023/8:30 James to cleaner
A 3/NOV/2023/10:00 Steven to teacher
A 3/NOV/2023/10:00 John to teacher
A 3/NOV/2023/10:00 Renia to cleaner
A 4/NOV/2023/8:30 Steven to teacher
A 4/NOV/2023/8:30 John to teacher
A 4/NOV/2023/8:30 Renia to cleaner
A 5/NOV/2023/10:00 Andrew to teacher
A 5/NOV/2023/10:00 James to teacher
A 5/NOV/2023/10:00 Janusz to cleaner

**Comment by rejkid** [comment]
F-stands for max flow H for Hungarian algorithm. What does A stand for?

**Comment by JamesBremner** [comment]
A = agent2tasks

**Comment by JamesBremner** [comment]
Please read title of issue.

**Comment by rejkid** [comment]
Distribute does not mean evenly - that is my question

**Comment by JamesBremner** [comment]
If there are multiple agents of equal cost available to do a task, the task will be assigned to the agent with the fewest assignments in the previous timeslots.  

So the uneven distribution of work to agents when there are more agents than work and the agents have the same cost per assignment will decrease as a percentage of total assignments as the number of timeslots increases with a limit of +/- 1 assignments per agent.

**Comment by rejkid** [comment]
My testing is positive. I have tested various configuration and every time the result was satisfying.

An example is included here: where I encoded into user some more information that I need later when populating SQLite database with my structures.
[example_output.txt](https://github.com/JamesBremner/Agents2Tasks/files/13301554/example_output.txt)
