### ISSUE TITLE
Converting GUI to command line tool

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#6]
Could we convert the GUI to the command line tool so the Agents2Tasks can be used by third party apps to generate results without human interaction.
The command line should take the two parameters:
1) Input file name
2) Result file name

**Comment by rejkid** [comment]
I have run the task:
.\Agents2Tasks.exe example.txt example_result.txt
No output in the form of example_result.txt has been generated. The GUI still popups.

**Comment by JamesBremner** [comment]
You need to run and build the console application.

**Comment by JamesBremner** [comment]
To build the console app

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/f967088b-8a96-4c7e-b152-13f7c42b662c)

**Comment by rejkid** [comment]
Run as: .\Agents2TasksConsole.exe example.txt example_result.txt
Tested with the attached input file. Results also included. Passed.

[example.txt](https://github.com/JamesBremner/Agents2Tasks/files/13309018/example.txt)
[example_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/13309019/example_result.txt)
