### ISSUE TITLE
No output generated for a complex file

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#7]
[agents2Tasks.txt](https://github.com/JamesBremner/Agents2Tasks/files/13303507/agents2Tasks.txt)

I have this non trivial input file which generates no output at all using Agents2Tasks tool.

**Comment by JamesBremner** [comment]
for the file format docs

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/b3aa5c74-eea8-4f41-aa94-6210e9ff52a2)

**Comment by rejkid** [comment]
Run the test. Both input and result files are included.
[agents2Tasks.txt](https://github.com/JamesBremner/Agents2Tasks/files/13309153/agents2Tasks.txt)
[agents2Tasks_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/13309154/agents2Tasks_result.txt)

The problem with the result that I see in this case is that Irene_Smith is assigned twice the same day (22/Oct/2023/8:30 and 22/Oct/2023/10:00) as Acolyte while there is another Acolyte not used yet like John_Black.
![explanation](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/8cef9ecf-e6d7-4d6e-b6fc-a4fbf3a9a0e5)

**Comment by JamesBremner** [comment]
Irene_Smith  is assigned in different timeslots.

**Comment by rejkid** [comment]
I see you point. However from the practical point of view she can't attend her duty twice a day. Is there anything we could do about it?

**Comment by JamesBremner** [comment]
I asked you about this.  It was the first question I asked you on StackOverflow.  You said that tasks do not overlap timeslots.

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/e77cd273-9f49-4f81-8fb2-b829e96703a5)

So the algorithms assume that timeslots are independent.  It is in the first line of the documentation

![image](https://github.com/JamesBremner/Agents2Tasks/assets/2046227/108276ac-7816-4ce1-8c8a-ed26e17db394)

If you want me to implement a new algorithm where tasks do overlap timeslots, please open a new issue, so we can discuss the details of what you want.

This issues can be closed in my opinion.

**Comment by rejkid** [comment]
Yep. My fault. Sorry about this. I am closing the issue.
