### ISSUE TITLE
One MAS task assigned but two MAS tasks requested in the time slot for 202310221000

### ISSUE THREAD

**Issue by rejkid** [JamesBremner/Agents2Tasks#9]
For :
t **202310221000** Acolyte  **MAS MAS** Reader1 Reader2 EMHC  
I have requested two MAS tasks but only one has been assigned - see the image and the result file.

[a2t_result.txt](https://github.com/JamesBremner/Agents2Tasks/files/13315835/a2t_result.txt)

![issue](https://github.com/JamesBremner/Agents2Tasks/assets/29744306/76cb43ab-207f-4900-be08-35a744bba8a2)

**Comment by JamesBremner** [comment]
You have three agents that can do 'MAS'

Two of them are assigned to 'MAS' in timeslot  202310220830 so they are unavailable for timeslot  202310221000 leaving just one.

**Comment by rejkid** [comment]
Sorry. You are right.
